export const billingPage = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>简辑 · 会员续费</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fc;color:#18263c;font:16px/1.7 system-ui,sans-serif}main{max-width:1040px;margin:40px auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{font-size:32px;margin:4px 0}h2{font-size:21px}section,.request{background:white;border:1px solid #dce3ef;border-radius:16px;padding:24px;margin:20px 0}label{display:block;margin:12px 0}input,select,button,a.button{font:inherit;padding:10px 14px;border:1px solid #c5d0e3;border-radius:8px}input:not([type=checkbox]),select{max-width:100%;width:100%}button,a.button{cursor:pointer;background:#315ccb;color:white;text-decoration:none}button:disabled{opacity:.5;cursor:wait}button.secondary{background:white;color:#315ccb;margin-left:8px}.muted{color:#617089}.notice{background:#eef3ff;padding:14px;border-radius:10px}.error{color:#ad2020}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.qr{display:block;max-width:100%;max-height:440px;margin:auto;object-fit:contain}.request{margin:12px 0;padding:18px}.request p{margin:4px 0;overflow-wrap:anywhere}[hidden]{display:none!important}#message{white-space:pre-wrap}input[type=checkbox]{margin-right:8px}@media(max-width:680px){main{padding:14px;margin:12px auto}.grid{grid-template-columns:1fr}header{align-items:flex-start;flex-wrap:wrap}section{padding:18px}h1{font-size:27px}}
</style><script src="/billing/app.js" defer></script></head><body><main>
<header><div><strong>简辑 · 账号中心</strong><h1>会员续费</h1></div><div id="identity" class="muted"></div></header>
<p id="message" role="status" aria-live="polite"></p>
<section id="login"><h2>登录后提交付款申请</h2><p>月度会员 ¥100，年度会员 ¥666；新账号免费试用一个月。</p><a class="button" href="/billing/login">登录 / 注册</a><p class="muted">同一账号新登录会使旧会话失效。从简辑内打开续费页可沿用当前登录。</p></section>
<div id="workspace" hidden><section><h2>选择套餐与付款方式</h2><p class="notice">付款由管理员人工核对。提交申请不会自动开通，请勿重复付款。审核后从现有权益到期时间续期。</p>
<div class="grid"><form id="submit"><label>会员套餐<select id="plan"><option value="monthly">月度会员 · ¥100</option><option value="yearly">年度会员 · ¥666</option></select></label><label>付款方式<select id="channel"><option value="wechat">微信支付</option><option value="alipay">支付宝</option></select></label><p id="amount"><strong>请扫码支付 ¥100</strong></p><label>付款订单号<input id="transaction" required minlength="8" maxlength="80" pattern="[A-Za-z0-9_-]+" autocomplete="off" placeholder="从微信或支付宝账单详情复制完整单号"></label><p class="muted">请确认收款人信息与二维码一致。不要填写银行卡号、密码或验证码。</p><button type="submit">已付款，提交审核</button></form><div><img id="qr" class="qr" alt="微信收款码" src="/billing/qr/wechat"><p class="muted">请用手机扫描原图，按所选套餐输入金额。</p></div></div></section>
<section><header><h2 id="list-title">我的申请</h2><button id="refresh" class="secondary">刷新状态</button></header><p id="admin-note" class="notice" hidden>请在微信或支付宝收款账单中核对付款单号、收款金额及付款人。用户提交的信息不代表已到账。</p><div id="requests"></div></section><button id="logout" class="secondary">退出此页面</button></div>
</main></body></html>`;

export const billingScript = `"use strict";
let csrf='',busy=false;
const $=id=>document.getElementById(id);
const message=(text,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'notice';};
async function api(path,body){const response=await fetch('/billing/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined,redirect:'error'});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作未完成，请刷新查看。');return data;}
async function work(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function line(parent,label,value){const p=document.createElement('p');p.textContent=label+value;parent.append(p);}
async function refresh(){const data=await api('requests');csrf=data.csrf;$('login').hidden=true;$('workspace').hidden=false;$('identity').textContent=data.user.displayName||data.user.name;$('list-title').textContent=data.user.isAdmin?'付款申请审核':'我的申请';$('admin-note').hidden=!data.user.isAdmin;const list=$('requests');list.replaceChildren();if(!data.requests.length)line(list,'','暂无申请。');for(const r of data.requests){const card=document.createElement('article');card.className='request';line(card,'账号：',r.user);line(card,'套餐：',(r.plan==='monthly'?'月度':'年度')+' · ¥'+r.amount);line(card,'付款渠道：',r.channel==='wechat'?'微信':'支付宝');line(card,'付款单号：',r.transaction);line(card,'状态：',({pending:'待人工核款',approved:'已审核开通',rejected:'未通过'})[r.state]);if(r.audit)line(card,'审核说明：',r.audit.note);if(r.state==='approved')line(card,'有效期：',new Date(r.startTime).toLocaleString('zh-CN',{hour12:false})+' 至 '+new Date(r.endTime).toLocaleString('zh-CN',{hour12:false}));if(data.user.isAdmin&&r.state==='pending'){const form=document.createElement('form');const amountLabel=document.createElement('label');amountLabel.textContent='实际到账金额（元）';const amount=document.createElement('input');amount.type='number';amount.min='0';amount.step='0.01';amount.required=true;amountLabel.append(amount);const receivedLabel=document.createElement('label');const received=document.createElement('input');received.type='checkbox';receivedLabel.append(received,document.createTextNode('我已从收款账单核实实际到账及付款单号'));const noteLabel=document.createElement('label');noteLabel.textContent='核款说明 / 拒绝原因';const note=document.createElement('input');note.maxLength=200;note.required=true;noteLabel.append(note);const approve=document.createElement('button');approve.textContent='确认到账并开通';approve.type='submit';const reject=document.createElement('button');reject.textContent='拒绝申请';reject.type='button';reject.className='secondary';async function review(action){if(!note.value.trim()){message('请填写审核说明。',true);return;}await work(async()=>{await api('requests/'+r.id+'/review',{action,received:received.checked,amount:Number(amount.value),note:note.value});message(action==='approve'?'审核已保存，会员期限已安排。':'已拒绝申请。');await refresh();});}form.onsubmit=e=>{e.preventDefault();void review('approve');};reject.onclick=()=>void review('reject');form.append(amountLabel,receivedLabel,noteLabel,approve,reject);card.append(form);}list.append(card);}}
$('channel').onchange=()=>{$('qr').src='/billing/qr/'+$('channel').value;$('qr').alt=$('channel').value==='wechat'?'微信收款码':'支付宝收款码';};
$('plan').onchange=()=>{$('amount').textContent='请扫码支付 ¥'+($('plan').value==='monthly'?100:666);};
$('submit').onsubmit=e=>{e.preventDefault();void work(async()=>{await api('requests',{plan:$('plan').value,channel:$('channel').value,transaction:$('transaction').value.trim()});message('申请已提交，等待管理员核款。请勿重复付款。');await refresh();});};
$('refresh').onclick=()=>void work(refresh);
$('logout').onclick=()=>void work(async()=>{await api('logout',{});location.assign('/billing');});
void work(async()=>{if(location.hash.startsWith('#ticket=')){const ticket=location.hash.slice(8);history.replaceState(null,'','/billing');await api('session',{ticket});}await refresh();});
`;
