import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ConnectionStore } from "../src/main/connection-store";
import { ModelConnections } from "../src/main/model-connections";
import { DEFAULT_QWEN_CONNECTION } from "../src/shared/connections";

const directories: string[] = [];
const input = { name: "My provider", model: "vision", baseUrl: "https://example.test/v1", apiKey: "private-test-key", protocol: "responses" as const };
async function setup() { const directory = await mkdtemp(path.join(tmpdir(), "jianji-connections-")); directories.push(directory); const store = new ConnectionStore(directory); await store.load(); return { directory, store }; }
afterEach(async () => { await Promise.all(directories.splice(0).map((d) => rm(d, { recursive: true, force: true }))); });
describe("built-in connections", () => {
  it("activates the default team Qwen on first credential save, persists it, and respects disconnect", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.restore();
    expect(connections.provider.status().configured).toBe(false);
    await connections.save({ ...DEFAULT_QWEN_CONNECTION, apiKey: "private-member-fixture-key" });
    expect(connections.provider.status()).toMatchObject({ configured: true, baseUrl: DEFAULT_QWEN_CONNECTION.baseUrl, model: DEFAULT_QWEN_CONNECTION.model });
    expect(JSON.stringify(connections.store.snapshot())).not.toContain("private-member-fixture-key");
    const restored = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await restored.restore();
    expect(restored.provider.status().model).toBe(DEFAULT_QWEN_CONNECTION.model);
    await restored.disconnect();
    const disconnected = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await disconnected.restore();
    expect(disconnected.provider.status().configured).toBe(false);
    expect(disconnected.store.snapshot().profiles).toHaveLength(1);
    await connections.dispose(); await restored.dispose(); await disconnected.dispose();
  });
  it("requires a private Key and preserves an existing explicit connection when adding team Qwen", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.restore();
    await expect(connections.save(DEFAULT_QWEN_CONNECTION)).rejects.toThrow("API Key");
    expect(connections.store.snapshot().profiles).toHaveLength(0);
    await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id;
    await connections.select(id);
    await connections.save({ ...DEFAULT_QWEN_CONNECTION, apiKey: "private-member-fixture-key" });
    expect(connections.store.snapshot().selected).toBe(id);
    expect(connections.provider.status().model).toBe(input.model);
    await connections.dispose();
  });
  it("persists and clears model effort while preserving credentials and ordinary profile edits", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id; await connections.select(id);
    await connections.selectModel({ connectionId: id, model: "vision", reasoningEffort: "high" });
    expect(connections.provider.status().reasoningEffort).toBe("high");
    await connections.save({ ...input, id, name: "renamed" });
    expect(connections.provider.status().reasoningEffort).toBe("high");
    const restored = new ModelConnections(directory, process.cwd(), async () => {}, () => {}); await restored.restore();
    expect(restored.provider.status().reasoningEffort).toBe("high");
    expect(restored.store.get(id).input.apiKey).toBe(input.apiKey);
    await restored.selectModel({ connectionId: id, model: "vision" });
    expect(restored.provider.status().reasoningEffort).toBeUndefined();
    await restored.store.saveChatGPTModel("vision", "ultra");
    const store = new ConnectionStore(path.join(directory, "connections")); await store.load();
    expect(store.snapshot().chatgptReasoningEffort).toBe("ultra");
    await connections.dispose(); await restored.dispose();
  });
  it("keeps the active model when saving fails and blocks competing operations while saving", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id; await connections.select(id);
    let reject!: (error: Error) => void;
    vi.spyOn(connections.store, "save").mockImplementationOnce(() => new Promise((_, no) => { reject = no; }));
    const switching = connections.selectModel({ connectionId: id, model: "vision-next" });
    const failed = expect(switching).rejects.toThrow("disk-full");
    expect(() => connections.assertIdle()).toThrow();
    await expect(connections.selectModel({ connectionId: id, model: "another" })).rejects.toThrow();
    reject(new Error("disk-full")); await failed;
    expect(connections.provider.status().model).toBe("vision");
    expect(connections.store.get(id).input.model).toBe("vision");
    expect(() => connections.assertIdle()).not.toThrow(); await connections.dispose();
  });
  it("switches the active API model without changing credentials, persists it, and rejects stale selections", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id; await connections.select(id);
    await connections.selectModel({ connectionId: id, model: "vision-next" });
    expect(connections.provider.status().model).toBe("vision-next");
    expect(connections.store.get(id).input.apiKey).toBe(input.apiKey);
    await expect(connections.selectModel({ connectionId: "chatgpt", model: "vision" })).rejects.toThrow();
    await expect(connections.selectModel({ connectionId: id, model: " " })).rejects.toThrow();
    const restored = new ModelConnections(directory, process.cwd(), async () => {}, () => {}); await restored.restore();
    expect(restored.provider.status().model).toBe("vision-next");
    expect(JSON.stringify(restored.store.snapshot())).not.toContain(input.apiKey);
    await connections.dispose(); await restored.dispose();
  });
  it("persists a ChatGPT preference alongside API profiles", async () => {
    const { directory, store } = await setup();
    await store.select("chatgpt"); await store.saveChatGPTModel("vision-next"); await store.save(input);
    const restored = new ConnectionStore(directory); await restored.load();
    expect(restored.snapshot().chatgptModel).toBe("vision-next");
    expect(restored.snapshot().selected).toBe("chatgpt");
  });
  it("retains legacy ChatGPT selection when an inactive API profile is saved", async () => {
    const { directory } = await setup(); await mkdir(path.join(directory, "codex"));
    await writeFile(path.join(directory, "codex", "auth.json"), "fixture-only");
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    vi.spyOn(connections.chatgpt, "refresh").mockResolvedValue(true);
    await connections.restore(); await connections.save(input);
    const restored = new ConnectionStore(path.join(directory, "connections")); await restored.load();
    expect(restored.snapshot().selected).toBe("chatgpt"); await connections.dispose();
  });
  it("persists selection across restart without exposing keys in public state", async () => {
    const { directory, store } = await setup(); const id = await store.save(input); await store.select(id);
    const restored = new ConnectionStore(directory); await restored.load();
    expect(restored.snapshot().selected).toBe(id); expect(restored.get(id).input.apiKey).toBe(input.apiKey);
    expect(JSON.stringify(restored.snapshot())).not.toContain(input.apiKey);
    if (process.platform !== "win32") expect((await stat(path.join(directory, "connections.json"))).mode & 0o777).toBe(0o600);
  });
  it("preserves keys during editing and supports explicit replacement and deletion", async () => {
    const { store } = await setup(); const id = await store.save(input); await store.select(id);
    const { apiKey: _, ...edit } = input;
    await store.save({ ...edit, id, model: "vision-next" }); expect(store.get(id).input.apiKey).toBe(input.apiKey);
    await store.save({ ...edit, id, apiKey: "replacement" }); expect(store.get(id).input.apiKey).toBe("replacement");
    await store.remove(id); expect(store.snapshot()).toMatchObject({ profiles: [], selected: null });
    await expect(store.select(id)).rejects.toThrow("找不到");
  });
  it("rejects incomplete new profiles, unknown edits, and corrupt stores without replacing data", async () => {
    const { store, directory } = await setup(); const { apiKey: _, ...noKey } = input;
    await expect(store.save(noKey)).rejects.toThrow("API Key");
    await expect(store.save({ ...input, id: "00000000-0000-4000-8000-000000000000" })).rejects.toThrow("不存在");
    await writeFile(path.join(directory, "connections.json"), "corrupt-secret-data");
    const restored = new ConnectionStore(directory); await restored.load();
    expect(restored.snapshot().error).toContain("无法读取");
    await expect(restored.save(input)).rejects.toThrow("无法读取");
    expect(await readFile(path.join(directory, "connections.json"), "utf8")).toBe("corrupt-secret-data");
  });
  it("restores and switches independent API profiles without CC Switch or OAuth", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => { throw new Error("Unexpected browser login"); }, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id;
    await connections.select(id); expect(connections.provider.status()).toMatchObject({ source: "api", configured: true, model: "vision" });
    await connections.save({ ...input, id, model: "edited" }); expect(connections.provider.status().model).toBe("edited");
    const second = new ModelConnections(directory, process.cwd(), async () => {}, () => {}); await second.restore();
    expect(second.provider.status().model).toBe("edited");
    await second.disconnect(); expect(second.store.snapshot().profiles).toHaveLength(1);
    const third = new ModelConnections(directory, process.cwd(), async () => {}, () => {}); await third.restore();
    expect(third.provider.status().configured).toBe(false);
    await connections.dispose(); await second.dispose(); await third.dispose();
  });
  it("persists an independent API reviewer, clears it when its profile is removed, and disposes it", async () => {
    const { directory } = await setup();
    const connections = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id;
    await connections.select(id);
    await connections.selectReviewer({ connectionId: id, model: "reviewer", reasoningEffort: "high" });
    expect(connections.provider.status().model).toBe("vision");
    expect(connections.reviewerProvider.status()).toMatchObject({ configured: true, source: "api", model: "reviewer", reasoningEffort: "high" });
    expect(JSON.stringify(connections.store.snapshot())).not.toContain(input.apiKey);
    const restored = new ModelConnections(directory, process.cwd(), async () => {}, () => {});
    await restored.restore();
    expect(restored.reviewerProvider.status().model).toBe("reviewer");
    await restored.disconnect();
    expect(restored.provider.status().configured).toBe(false);
    expect(restored.reviewerProvider.status().configured).toBe(true);
    await restored.remove(id);
    expect(restored.store.snapshot().reviewer).toBeNull();
    expect(restored.reviewerProvider.status().configured).toBe(false);
    await connections.dispose(); await restored.dispose();
    expect(restored.reviewerProvider.status().configured).toBe(false);
  });
  it("keeps a ChatGPT reviewer selection independent and accepts old stores without reviewer", async () => {
    const { directory } = await setup();
    await writeFile(path.join(directory, "connections.json"), JSON.stringify({ version: 1, selected: null, profiles: [] }));
    const legacy = new ConnectionStore(directory); await legacy.load();
    expect(legacy.snapshot().reviewer).toBeNull();
    const connections = new ModelConnections(path.join(directory, "runtime"), process.cwd(), async () => {}, () => {});
    await connections.store.load(); await connections.save(input);
    const id = connections.store.snapshot().profiles[0].id; await connections.select(id);
    vi.spyOn(connections.chatgpt, "assertModel").mockImplementation(() => undefined);
    await connections.selectReviewer({ connectionId: "chatgpt", model: "reviewer-chatgpt", reasoningEffort: "high" });
    expect(connections.provider.status()).toMatchObject({ configured: true, source: "api", model: "vision" });
    expect(connections.reviewerProvider.status()).toMatchObject({ configured: true, source: "chatgpt", model: "reviewer-chatgpt", reasoningEffort: "high" });
    expect(connections.store.snapshot().reviewer).toEqual({ connectionId: "chatgpt", model: "reviewer-chatgpt", reasoningEffort: "high" });
    await expect(connections.selectReviewer({ connectionId: crypto.randomUUID(), model: "reviewer" })).rejects.toThrow("找不到");
    await connections.dispose();
  });
});
