import { LIBRARY_STICKERS, type LibraryAsset } from "./asset-library";

// Discovery-only allowlist. The complete manifest remains valid for saved jobs.
// Each concept has one neutral/default variant; additions require editorial review.
export const STICKER_SELECTION: ReadonlyArray<readonly [string, string, string]> = [
  ["Fire", "热卖火焰", "促销 爆款"],
  ["Shopping bags", "购物袋", "促销 好物"],
  ["Shopping cart", "购物车", "促销 下单"],
  ["Wrapped gift", "礼物", "促销 赠品"],
  ["Label", "价签", "促销 价格 优惠"],
  ["Ticket", "优惠券", "促销 券"],
  ["Money bag", "钱袋", "促销 省钱"],
  ["Coin", "硬币", "促销 省钱"],
  ["Party popper", "庆祝礼花", "促销 上新"],
  ["Confetti ball", "彩纸礼球", "促销 庆祝"],
  ["Megaphone", "扩音器", "促销 通知"],
  ["Loudspeaker", "喇叭", "促销 通知"],
  ["Hundred points", "满分", "强调 推荐"],
  ["Thumbs up", "点赞", "强调 推荐"],
  ["Clapping hands", "鼓掌", "强调 推荐"],
  ["Ok hand", "满意手势", "强调 推荐"],
  ["Check mark button", "确认勾选", "强调 重点"],
  ["Check mark", "对勾", "强调 重点"],
  ["Crown", "皇冠", "强调 精选"],
  ["Gem stone", "宝石", "强调 品质"],
  ["Light bulb", "灯泡", "强调 提示 灵感"],
  ["Eyes", "关注眼睛", "指引 看这里"],
  ["Index pointing at the viewer", "指向你", "指引 关注"],
  ["Backhand index pointing down", "向下手指", "指引 下单"],
  ["Backhand index pointing right", "向右手指", "指引 看这里"],
  ["Backhand index pointing left", "向左手指", "指引 看这里"],
  ["Backhand index pointing up", "向上手指", "指引 看这里"],
  ["Down arrow", "向下箭头", "指引 下单"],
  ["Right arrow", "向右箭头", "指引 重点"],
  ["Left arrow", "向左箭头", "指引 重点"],
  ["Up arrow", "向上箭头", "指引 重点"],
  ["Bell", "提醒铃铛", "指引 提醒"],
  ["Alarm clock", "闹钟", "指引 限时"],
  ["Stopwatch", "秒表", "指引 限时"],
  ["Hourglass not done", "沙漏", "指引 限时"],
  ["Sparkles", "闪光", "轻装饰 星星"],
  ["Star", "星星", "轻装饰"],
  ["Glowing star", "发光星星", "轻装饰"],
  ["Ribbon", "蝴蝶结", "轻装饰 礼物"],
  ["Balloon", "气球", "轻装饰 庆祝"],
  ["Butterfly", "蝴蝶", "轻装饰 蝴蝶贴"],
  ["Cherry blossom", "樱花", "轻装饰 清新"],
  ["Blossom", "小花", "轻装饰 清新"],
  ["Tulip", "郁金香", "轻装饰 清新"],
  ["Sunflower", "向日葵", "轻装饰 活力"],
  ["Four leaf clover", "四叶草", "轻装饰 清新"],
  ["Leaf fluttering in wind", "绿叶", "轻装饰 清新"],
  ["Red heart", "红色爱心", "正向情绪 喜欢 心动"],
  ["Pink heart", "粉色爱心", "正向情绪 喜欢 心动"],
  ["White heart", "白色爱心", "正向情绪 喜欢 简约"],
  ["Sparkling heart", "闪亮爱心", "正向情绪 喜欢 心动"],
  ["Heart with ribbon", "礼物爱心", "正向情绪 喜欢 赠品"],
  ["Two hearts", "双爱心", "正向情绪 喜欢 心动"],
  ["Smiling face with heart-eyes", "心动表情", "正向情绪 喜欢 推荐"],
  ["Smiling face with hearts", "幸福表情", "正向情绪 喜欢 满意"],
  ["Star-struck", "惊喜表情", "正向情绪 喜欢 推荐"],
  ["Rocket", "上升火箭", "强调 活力 上新"],
  ["Collision", "撞色爆闪", "强调 重点 波普"],
  ["Dizzy", "环绕星芒", "轻装饰 星星"],
  ["Heart decoration", "爱心徽章", "正向情绪 喜欢"],
  ["Orange heart", "橙色爱心", "正向情绪 心动 暖色"],
  ["Yellow heart", "黄色爱心", "正向情绪 心动 奶油"],
  ["Green heart", "绿色爱心", "正向情绪 心动 清新"],
  ["Blue heart", "蓝色爱心", "正向情绪 心动 清爽"],
  ["Purple heart", "紫色爱心", "正向情绪 心动 浪漫"],
  ["Light blue heart", "浅蓝爱心", "正向情绪 心动 清爽"],
  ["Smiling face with sunglasses", "酷酷表情", "正向情绪 潮流"],
  ["Beaming face with smiling eyes", "开心笑脸", "正向情绪 满意"],
  ["Winking face", "眨眼表情", "正向情绪 互动"],
  ["Face savoring food", "美味表情", "正向情绪 美食"],
  ["Face blowing a kiss", "飞吻表情", "正向情绪 喜欢"],
  ["Grinning face with big eyes", "灿烂笑脸", "正向情绪 开心"],
  ["Raising hands", "欢呼双手", "正向情绪 庆祝 互动"],
  ["Heart hands", "双手比心", "正向情绪 心动 互动"],
  ["Sparkler", "仙女棒", "轻装饰 节庆 星星"],
  ["Fireworks", "缤纷烟花", "轻装饰 节庆 庆祝"],
  ["Trophy", "金色奖杯", "强调 金色 装饰"],
  ["Sports medal", "星星奖牌", "强调 星星 装饰"],
  ["Sun", "元气太阳", "轻装饰 活力 夏日"],
  ["Rainbow", "缤纷彩虹", "轻装饰 清新 彩色"],
  ["Cloud", "棉花云朵", "轻装饰 柔软 清新"],
  ["Snowflake", "晶莹雪花", "轻装饰 冬日 清爽"],
  ["Droplet", "清透水滴", "轻装饰 清爽 蓝色"],
  ["Water wave", "蓝色浪花", "轻装饰 夏日 清爽"],
  ["Rose", "红玫瑰", "轻装饰 浪漫 花卉"],
  ["Hibiscus", "粉色扶桑", "轻装饰 花卉 夏日"],
  ["Bouquet", "缤纷花束", "轻装饰 花卉 礼物"],
  ["Seedling", "新芽", "轻装饰 清新 绿色"],
  ["Herb", "香草枝叶", "轻装饰 清新 植物"],
  ["Maple leaf", "秋日枫叶", "轻装饰 秋季 暖色"],
  ["Fallen leaf", "飘落秋叶", "轻装饰 秋季 暖色"],
  ["Cactus", "可爱仙人掌", "轻装饰 绿色 植物"],
  ["Palm tree", "夏日棕榈", "轻装饰 夏日 植物"],
  ["Lotus", "粉色莲花", "轻装饰 花卉 国风"],
  ["Red paper lantern", "红灯笼", "轻装饰 节庆 国风"],
  ["Wind chime", "清风铃铛", "轻装饰 夏日 清新"],
  ["Crystal ball", "星光水晶球", "轻装饰 星星 梦幻"],
  ["Magic wand", "星光魔法棒", "指引 星星 梦幻"],
];

export const CURATED_STICKERS: Array<LibraryAsset & { searchTerms: string }> = STICKER_SELECTION.flatMap(([name, label, keywords]) => {
  const asset = LIBRARY_STICKERS.find((candidate) => {
    const resource = decodeURIComponent(candidate.url.split("/assets/")[1] ?? "");
    return resource.startsWith(`${name}/3D/`) || resource.startsWith(`${name}/Default/3D/`);
  });
  // Missing upstream concepts are omitted, never replaced with a different sticker.
  return asset ? [{ ...asset, label, searchTerms: `${name} ${keywords}` }] : [];
});

// Custom bundled stickers (user-provided, packaged with installer).
const customStickers = LIBRARY_STICKERS.filter((asset) => asset.license === "custom");
CURATED_STICKERS.push(...customStickers.map((asset, index) => ({
  ...asset,
  label: `自定义 ${index + 1}`,
  searchTerms: `自定义 custom ${index + 1}`,
})));
