import assert from "node:assert/strict";
import { spawn, execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, symlink, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createServer } from "node:http";
import { createServer as createSocketServer } from "node:net";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { knowledgeProviderFixture, runKnowledgeSmoke } from "./source-sticker-knowledge-smoke.mjs";

// Real Electron/IPC/FFmpeg smoke; only the provider and native file picker are fixtures.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const directory = await mkdtemp(path.join(tmpdir(), "jianji-desktop-smoke-"));
const source = path.join(directory, "测试素材.mp4");
const output = path.join(directory, "output");
const collectionFile = path.join(directory, "夏季新品.jianji-project.json");
const smokeScope = process.env.JIANJI_SMOKE_SCOPE ?? "windows-retest";
const knowledgeFixture = knowledgeProviderFixture();
if (smokeScope === "knowledge") await symlink(path.join(root, "resources"), path.join(directory, "resources"), "junction");
execFileSync(process.env.JIANJI_FFMPEG_PATH || "ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "testsrc=size=1280x720:rate=24", "-t", "4", "-c:v", "libx264", "-pix_fmt", "yuv420p", source]);
const sourceBytes = await readFile(source);
const uploadSource = path.join(directory, "uploaded-heart.png");
execFileSync(process.env.JIANJI_FFMPEG_PATH || "ffmpeg", ["-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=red:s=64x64", "-frames:v", "1", uploadSource]);
let requests = 0;
let briefRequests = 0;
let shortlistRequests = 0;
let coverRequests = 0;
let supervisorRequests = 0;
let checkSupervisorAdmission;
let briefPayload;
let failBrief = false;
const server = createServer((request, response) => {
  let body = "";
  request.on("data", (chunk) => { body += chunk; });
  request.on("end", async () => {
    const input = JSON.parse(body);
    if (smokeScope === "knowledge") { await knowledgeFixture.respond(input, response); return; }
    const anthropic = request.url === "/anthropic/v1/messages";
    assert.equal(request.url, anthropic ? "/anthropic/v1/messages" : "/v1/chat/completions");
    const userContent = input.messages[anthropic ? 0 : 1].content;
    const systemText = anthropic ? input.system : input.messages[0].content;
    if (systemText.includes("你是视频包装主管 Agent")) {
      supervisorRequests++;
      assert.equal(JSON.stringify(input).includes(directory), false, "supervisor never receives local paths");
      let result;
      if (systemText.includes("当前阶段是原贴纸识别")) {
        const context = JSON.parse(userContent[0].text.slice("检查上下文：".length).split("。原图时间：")[0]);
        result = { action: "resolve", reason: "fixture source review", frames: context.proposal };
      } else {
        await checkSupervisorAdmission();
        result = { action: "pass", reason: "fixture rendered preview review" };
        if (requests === 2) await unlink(source); // Formal export failure AFTER the verified preview.
      }
      const text = JSON.stringify(result);
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    if (systemText.includes("你是视频画面覆盖物追踪器")) {
      coverRequests++;
      assert.equal(JSON.stringify(input).includes(directory), false, "tracking never sends local paths");
      const times = userContent.flatMap(item => item.type === "text" && item.text.match(/^抽帧时间：(\d+)ms。$/) ? [Number(item.text.match(/^抽帧时间：(\d+)ms。$/)[1])] : []);
      assert.ok(times.length > 0 && times.length <= 8);
      const text = JSON.stringify({ status: "ok", frames: times.map(timeMs => ({ timeMs, targets: [
        { id: "one", rectangle: { x: 0.1 + timeMs / 20000, y: 0.1, width: 0.1, height: 0.1 } },
        { id: "two", rectangle: { x: 0.7, y: 0.7, width: 0.1, height: 0.1 } },
      ] })) });
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    if (systemText.includes("你是视频贴纸选材师")) {
      shortlistRequests += 1;
      const uploadText = userContent.find(item => item.type === "text" && item.text.includes("用户上传贴纸，目录编号"))?.text;
      const covering = systemText.includes("为原贴纸覆盖");
      if (!covering) assert.ok(uploadText, "automatic decoration shortlist receives uploaded artwork with its catalog number");
      assert.equal(userContent.filter(item => item.type === (anthropic ? "image" : "image_url")).length, uploadText ? 4 : 3);
      const entries = JSON.parse(systemText.split("完整目录为 [编号,名称,资格]：")[1]);
      const number = uploadText ? Number(uploadText.match(/目录编号 (\d+)/)[1]) : entries.find(entry => entry[1] === "爱心" && entry[2] === "允许")?.[0];
      assert.ok(number, "cover shortlist selects an allowed builtin when the previous uploaded cover is excluded");
      const text = JSON.stringify({ candidates: [number] });
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    if (systemText.includes("你是视频原贴纸覆盖层的选材师")) {
      const sticker = userContent.find(item => item.type === "text" && item.text.startsWith("候选贴纸 1，ID："))?.text.match(/ID：([^，]+)/)?.[1];
      assert.ok(sticker);
      const text = JSON.stringify({ sticker });
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    if (typeof userContent === "string" || systemText.includes("你是视频包装创意总监")) {
      assert.equal(request.headers.authorization, anthropic ? "Bearer cc-switch-fixture-key" : "Bearer local-smoke-key");
      briefRequests += 1; briefPayload = input;
      await new Promise(resolve => setTimeout(resolve, 300));
      response.setHeader("Content-Type", "application/json");
      if (failBrief) { response.writeHead(503); response.end('{}'); return; }
      const text = "保持清爽自然，保留已选贴纸与手动价格，按画面需要留白。";
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    assert.equal(input.messages[anthropic ? 0 : 1].content.filter((item) => item.type === (anthropic ? "image" : "image_url")).length, 4, "three video frames plus the actual uploaded sticker image");
    assert.equal(JSON.stringify(input).includes("用户手动选择的上传贴纸") || JSON.stringify(input).includes("贴纸候选"), true);
    assert.equal(JSON.stringify(input).includes(directory), false, "local upload paths never reach the provider");
    assert.equal(input.model, anthropic ? "MiniMax-M3" : "smoke-vision-next", "video analysis uses the selected model");
    if (!anthropic) assert.equal(input.reasoning_effort, "high", "video analysis uses selected effort");
    assert.equal(request.headers.authorization, anthropic ? "Bearer cc-switch-fixture-key" : "Bearer local-smoke-key");
    requests += 1;
    response.setHeader("Content-Type", "application/json");
    const automatic = systemText.includes('"stickers"');
    const sticker = JSON.stringify(userContent).match(/uploaded-[a-f0-9]{64}/)?.[0];
    const text = JSON.stringify({ summary: "保留主体与手动价格", captions: [], ...(automatic ? { stickers: ["top-left", "top-right", "bottom-left", "bottom-right"].map((corner) => ({ corner, sticker, width: 0.08, rotationDeg: 0 })), priceStyle: "ice" } : {}), filter: "cool", intensity: 0.3 });
    response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
  });
});
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const apiPort = server.address().port;
const fixtureHome = path.join(directory, "home");
await mkdir(path.join(fixtureHome, ".cc-switch"), { recursive: true });
const SQL = await require("sql.js/dist/sql-asm.js")();
const db = new SQL.Database();
db.run("CREATE TABLE providers (id TEXT, app_type TEXT, name TEXT, settings_config TEXT, is_current INTEGER)");
db.run("INSERT INTO providers VALUES (?, ?, ?, ?, 1)", ["fixture", "claude", "MiniMax fixture", JSON.stringify({ env: { ANTHROPIC_AUTH_TOKEN: "cc-switch-fixture-key", ANTHROPIC_BASE_URL: `http://127.0.0.1:${apiPort}/anthropic`, ANTHROPIC_MODEL: "MiniMax-M3" } })]);
await writeFile(path.join(fixtureHome, ".cc-switch", "cc-switch.db"), Buffer.from(db.export())); db.close();
const portServer = createSocketServer();
await new Promise((resolve) => portServer.listen(0, "127.0.0.1", resolve));
const debugPort = portServer.address().port;
await new Promise((resolve) => portServer.close(resolve));
const bootstrap = path.join(directory, "bootstrap.cjs");
await writeFile(path.join(directory, "recent-projects.json"), "{broken-index-fixture");
await writeFile(bootstrap, `const { app, dialog, shell } = require("electron");
process.chdir(${JSON.stringify(directory)});
app.setPath("documents", ${JSON.stringify(directory)});
const filePromises = require("node:fs/promises");
const originalWriteFile = filePromises.writeFile;
filePromises.writeFile = async (file, ...args) => {
  if (typeof file === "string" && file.includes("recent-projects.json.tmp-") && require("node:fs").existsSync(${JSON.stringify(path.join(directory, "index-failure"))})) throw new Error("ENOSPC: fixture recent index failure");
  if (typeof file === "string" && file.endsWith(".deleted")) {
    while (!require("node:fs").existsSync(${JSON.stringify(path.join(directory, "delete.release"))})) await new Promise(resolve => setTimeout(resolve, 10));
  }
  return originalWriteFile(file, ...args);
};
require("node:os").homedir = () => ${JSON.stringify(fixtureHome)};
const childProcess = require("node:child_process");
const nativeSpawn = childProcess.spawn;
childProcess.spawn = (command, args, options) => /[\\\\/]vendor[\\\\/].*[\\\\/]bin[\\\\/]codex(?:\\.exe)?$/.test(command) ? nativeSpawn(${JSON.stringify(process.execPath)}, [${JSON.stringify(path.join(root, "tests/fixtures/codex-app-server.cjs"))}, ${JSON.stringify(path.join(directory, "codex.pid"))}], options) : nativeSpawn(command, args, options);
shell.openExternal = async (url) => { if (!url.startsWith("https://auth.openai.com/")) throw new Error("Unexpected login URL"); };
shell.trashItem = async (file) => filePromises.rename(file, file + ".trashed");
app.setPath("userData", ${JSON.stringify(directory)});
require("node:fs").watch(${JSON.stringify(directory)}, (_event, name) => { if (name === "quit.signal") app.quit(); });
app.getAppPath = () => ${JSON.stringify(root)};
process.defaultApp = false;
process.resourcesPath = ${JSON.stringify(path.join(root, "resources"))}; // Resource fixture is independent of the isolated project cwd.
app.commandLine.appendSwitch("remote-debugging-port", ${JSON.stringify(String(debugPort))});
app.commandLine.appendSwitch("remote-debugging-address", "127.0.0.1");
let stickerPickerCalls = 0;
dialog.showOpenDialog = async (_window, options) => {
  if (options.title === "上传贴纸") {
    stickerPickerCalls += 1;
    return stickerPickerCalls === 1 ? { canceled: true, filePaths: [] } : { canceled: false, filePaths: [stickerPickerCalls === 2 ? ${JSON.stringify(source)} : ${JSON.stringify(uploadSource)}] };
  }
  if (options.title === "打开项目") await filePromises.writeFile(${JSON.stringify(path.join(directory, "project-picker.called"))}, "called");
  return { canceled: false, filePaths: options.properties.includes("openDirectory") ? [${JSON.stringify(output)}] : options.title === "打开项目" ? [${JSON.stringify(collectionFile)}] : [${JSON.stringify(source)}] };
};
dialog.showSaveDialog = async () => ({ canceled: false, filePath: ${JSON.stringify(collectionFile)} });
dialog.showMessageBox = async (_window, options) => ({ response: options.title === "删除项目" || ${JSON.stringify(smokeScope === "knowledge")} && options.title === "新建项目" || options.title === "保存项目更改？" && require("node:fs").existsSync(${JSON.stringify(path.join(directory, "index-failure"))}) ? 0 : 1 });
require(${JSON.stringify(path.join(root, "dist-electron/main.cjs"))});
`);
const environment = { ...process.env };
delete environment.ELECTRON_RUN_AS_NODE;
delete environment.JIANJI_DEV_SERVER_URL;
const child = spawn(require("electron"), [bootstrap], { cwd: root, env: environment, stdio: ["ignore", "pipe", "pipe"] });
let processLog = "";
child.stderr.on("data", (chunk) => { processLog += chunk.toString(); });
child.stdout.on("data", (chunk) => { processLog += chunk.toString(); });
const pause = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
let socket;
desktopSmoke: try {
  let target;
  for (let attempt = 0; attempt < 100; attempt++) {
    if (child.exitCode !== null) throw new Error(`Electron exited: ${processLog}`);
    try { target = (await (await fetch(`http://127.0.0.1:${debugPort}/json`)).json()).find((page) => page.type === "page"); } catch {}
    if (target) break;
    await pause(100);
  }
  assert.ok(target, processLog);
  socket = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener("open", resolve, { once: true }); socket.addEventListener("error", reject, { once: true }); });
  let sequence = 0;
  const pending = new Map();
  const exceptions = [];
  socket.addEventListener("message", (event) => {
    const message = JSON.parse(event.data);
    if (message.method === "Runtime.exceptionThrown") exceptions.push(message.params.exceptionDetails.text);
    if (message.id) {
      const entry = pending.get(message.id); pending.delete(message.id);
      if (message.error) entry?.reject(new Error(JSON.stringify(message.error)));
      else entry?.resolve(message.result);
    }
  });
  const send = (method, params = {}) => new Promise((resolve, reject) => {
    const id = ++sequence;
    const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP timeout: ${method}`)); }, 15_000);
    pending.set(id, { resolve: (value) => { clearTimeout(timer); resolve(value); }, reject: (error) => { clearTimeout(timer); reject(error); } });
    socket.send(JSON.stringify({ id, method, params }));
  });
  const evaluate = async (expression) => {
    const result = await send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true });
    if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
    return result.result.value;
  };
  checkSupervisorAdmission = async () => {
    const outcome = await evaluate("(async () => { try { await window.jianji.retryExport([]); return 'unexpected admission'; } catch (error) { return String(error); } })()");
    assert.ok(outcome.includes("Agent 正在处理"), "historical retries cannot interrupt supervisor rendering");
    await pause(100);
    assert.ok(await evaluate("document.querySelector('.result-info')?.textContent.includes('主管')"), "supervisor stage is visible in results");
    await evaluate("document.querySelector('.result-row:has(.status-tag.analyzing)')?.scrollIntoView({ block: 'center' })");
    const progressImage = await send("Page.captureScreenshot", { format: "png" });
    await writeFile(path.join(directory, "supervisor-progress.png"), Buffer.from(progressImage.data, "base64"));
  };
  const waitFor = async (expression) => {
    for (let attempt = 0; attempt < 200; attempt++) { if (await evaluate(expression)) return; await pause(100); }
    throw new Error(`Timed out: ${expression}; page: ${await evaluate("document.body?.innerText.slice(0, 500)")}; exceptions: ${exceptions.join(" | ")}`);
  };
  const click = async (text) => {
    const selector = `[...document.querySelectorAll('button')].find(button => button.textContent.includes(${JSON.stringify(text)}))`;
    assert.equal(await evaluate(`Boolean(${selector} && !${selector}.disabled)`), true, `Button unavailable: ${text}`);
    await evaluate(`${selector}.click()`);
    await pause(80);
  };
  const screenshot = async (name) => {
    await send("Page.bringToFront");
    const image = await send("Page.captureScreenshot", { format: "png" });
    await writeFile(path.join(directory, `${name}.png`), Buffer.from(image.data, "base64"));
  };
  await send("Runtime.enable");
  await waitFor("document.body?.innerText.includes('连接模型')");
  if (smokeScope === "knowledge") {
    await runKnowledgeSmoke({ evaluate, click, waitFor, send, screenshot, apiPort, directory, fixture: knowledgeFixture });
    assert.deepEqual(exceptions, []);
    assert.deepEqual(await readFile(source), sourceBytes);
    break desktopSmoke;
  }
  assert.equal(await evaluate("document.body.innerText.includes('已保存项目列表暂时无法读取')"), true, "a corrupt index must not prevent desktop startup");
  await click("贴纸库");
  await waitFor("document.body.innerText.includes('还没有上传贴纸')");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].some(button => button.textContent === '选择图片上传' && !button.disabled)"), true, "standalone sticker library is available without a model or video");
  await screenshot("00-sticker-library-empty");
  await click("选择图片上传");
  await waitFor("!document.body.innerText.includes('正在上传…')");
  assert.equal(await evaluate("document.querySelectorAll('.uploaded-sticker-grid img').length"), 0, "cancel preserves empty library");
  await click("选择图片上传");
  await waitFor("document.querySelector('[role=alert]')?.textContent.includes('上传失败')");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].some(button => button.textContent === '选择图片上传' && !button.disabled)"), true, "invalid upload can be retried");
  await click("制作");
  const duplicate = spawn(require("electron"), [bootstrap], { cwd: root, env: environment, stdio: "ignore" });
  const duplicateExit = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => { duplicate.kill(); reject(new Error("Second instance failed to exit")); }, 5000);
    duplicate.once("exit", (code) => { clearTimeout(timeout); resolve(code); });
  });
  assert.equal(duplicateExit, 0, "Second instance must leave the existing connection owner running");
  await screenshot("01-connection");
  assert.equal(await evaluate("[...document.querySelectorAll('[role=tab]')].find(button => button.textContent === 'API 连接管理').getAttribute('aria-selected')"), "true", "new installations default to the team API form");
  assert.equal(await evaluate("document.querySelector('.manual-connection input[type=url]').value"), "https://qwen.reggie-sun.ccwu.cc/v1");
  assert.equal(await evaluate("document.querySelector('.manual-connection input[type=password]').value"), "", "member credentials must not be bundled");
  assert.equal(await evaluate("[...document.querySelectorAll('.manual-connection input')].some(input => input.value === 'Qwen/Qwen3-VL-8B-Instruct')"), true);
  await click("ChatGPT 登录");
  await click("使用 ChatGPT 登录");
  await waitFor("[...document.querySelectorAll('button')].some(button => button.textContent.includes('取消登录') && !button.disabled)");
  if (smokeScope !== "windows-retest") await screenshot("01a-login-pending");
  await click("取消登录");
  await waitFor("document.body.innerText.includes('使用 ChatGPT 登录')");
  await click("使用 ChatGPT 登录");
  await waitFor("document.body.innerText.includes('smoke@example.test')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.source, "chatgpt");
  if (smokeScope === "windows-retest") {
    await click("开始创作");
    await waitFor("document.body.innerText.includes('选择本地素材')");
    await click("选择本地素材");
    await waitFor("document.body.innerText.includes('测试素材.mp4')");
    await click("下一步，设置制作规则");
    await waitFor("document.querySelector('#product-price') !== null");
    await click("本地随机");
    await evaluate("const price = document.querySelector('#product-price'); Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set.call(price, '春日新品'); price.dispatchEvent(new Event('input', { bubbles: true }))");
    await evaluate("const count = document.querySelector('#production-count'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(count, '1'); count.dispatchEvent(new Event('input', { bubbles: true }))");
    await evaluate("document.querySelector('.directory-picker').click()");
    await waitFor("document.querySelector('.directory-picker')?.textContent.includes('output')");
    await click("交给 Agent，制作 1 条成片");
    await waitFor("document.querySelector('.result-row .status-tag.completed') !== null");
    const state = await evaluate("window.jianji.getState()");
    const completed = state.queue.batches.flatMap(({ batch }) => batch.tasks).find((task) => task.status === "completed");
    assert.ok(completed?.outputPath, "local random export is completed");
    assert.equal(requests, 0, "local random export makes no model request");
    assert.deepEqual(await readFile(source), sourceBytes, "export preserves the source");
    assert.deepEqual(exceptions, [], "renderer has no runtime exceptions");
    await screenshot("windows-retest-completed");
    console.log(JSON.stringify({ result: "PASS", scope: smokeScope, output: completed.outputPath, screenshotDirectory: directory, providerRequests: requests, runtimeExceptions: exceptions }, null, 2));
    break desktopSmoke;
  }
  assert.deepEqual(await evaluate("[...document.querySelector('.model-picker select').options].map(option => option.value)"), ["", "smoke-codex-vision", "smoke-codex-next"]);
  await evaluate("document.querySelector('.model-picker select').value = 'smoke-codex-next'; document.querySelector('.model-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor("document.body.innerText.includes('创作模型已切换并保存')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-codex-next");
  assert.deepEqual(await evaluate("[...document.querySelector('.effort-picker select').options].map(option => option.value)"), ["", "medium", "xhigh", "ultra"], "efforts come from the chosen model");
  await evaluate("document.querySelector('.effort-picker select').value = 'xhigh'; document.querySelector('.effort-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor("document.querySelector('.effort-picker select').value === 'xhigh' && !document.querySelector('.effort-picker select').disabled");
  assert.equal((await evaluate("window.jianji.getState()")).connection.reasoningEffort, "xhigh");
  await click("刷新登录状态");
  assert.equal((await evaluate("window.jianji.getState()")).chatgpt.status, "ready");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-codex-next");
  assert.equal(JSON.parse(await readFile(path.join(directory, "connections/connections.json"), "utf8")).chatgptModel, "smoke-codex-next");
  assert.equal(JSON.parse(await readFile(path.join(directory, "connections/connections.json"), "utf8")).chatgptReasoningEffort, "xhigh");
  await screenshot("01b-chatgpt-ready");
  await click("断开");
  await waitFor("document.body.innerText.includes('使用 ChatGPT 登录')");
  await click("API 连接管理");
  await click("添加 API 连接");
  for (const [index, value] of ["Smoke API", `http://127.0.0.1:${apiPort}/v1/`, "smoke-vision", "local-smoke-key"].entries()) {
    await evaluate(`document.querySelectorAll('.connection-form input')[${index}].focus();document.querySelectorAll('.connection-form input')[${index}].select()`);
    await send("Input.insertText", { text: value });
  }
  await click("保存连接");
  await waitFor("document.body.innerText.includes('使用此连接')");
  await click("编辑");
  assert.equal(await evaluate("document.querySelector('input[type=password]').value"), "");
  await click("保存连接");
  await click("使用此连接");
  await waitFor("document.body.innerText.includes('把视频拖到这里')");
  await evaluate("(async () => { const state = await window.jianji.getState(); const { protocol, ...profile } = state.connections.profiles[0]; await window.jianji.saveConnection(profile); })()");
  assert.equal(await evaluate("localStorage.length"), 0);
  await click("选择本地素材");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  await evaluate("document.querySelector('[aria-label=\"项目名称\"]').focus(); document.querySelector('[aria-label=\"项目名称\"]').select()");
  await send("Input.insertText", { text: "夏季新品" });
  if (smokeScope === "saved-project-open") {
    await click("下一步");
    await click("自己设置");
    await click("海盐蓝调");
    await evaluate("document.querySelector('#decoration-display-mode').value = 'first-5s'; document.querySelector('#decoration-display-mode').dispatchEvent(new Event('change', { bubbles: true }))");
    await evaluate("document.querySelector('#creative-brief').focus()");
    await send("Input.insertText", { text: "恢复做到一半的提示" });
    await evaluate("document.querySelector('#export-format').value = 'mov'; document.querySelector('#export-format').dispatchEvent(new Event('change', { bubbles: true }))");
    await click("10 条");
  }
  await click("保存项目");
  await waitFor("document.body.innerText.includes('项目已保存')");
  const savedCollection = JSON.parse(await readFile(collectionFile, "utf8"));
  assert.equal(savedCollection.name, "夏季新品");
  assert.equal(savedCollection.mediaItems[0].displayName, "测试素材.mp4");
  assert.equal(savedCollection.mediaItems[0].sourcePath, source);
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  const blankProjectId = (await evaluate("window.jianji.getState()")).project.id;
  await evaluate("document.querySelector('[aria-label=\"查看素材\"]').click()");
  assert.equal(await evaluate("document.querySelector('nav button.active')?.textContent.includes('素材工作台')"), true, "folder button opens the material workspace");
  const savedEntry = (await evaluate("window.jianji.getState()")).recentProjects.find(entry => entry.name === "夏季新品");
  assert.ok(savedEntry, "saved project appears in the saved list");
  assert.equal(await evaluate(`document.querySelector('[data-recent-id=${JSON.stringify(savedEntry.id)}]') !== null`), true, "saved project is directly visible");
  if (smokeScope === "saved-project-manage") {
    await evaluate(`document.querySelector('[aria-label="已保存的项目"]').click(); document.querySelector('[aria-label=${JSON.stringify(`重命名项目 ${savedEntry.name}`)}]').click()`);
    assert.equal((await evaluate("window.jianji.getState()")).project.id, blankProjectId, "renaming a saved project does not load it");
    assert.equal((await evaluate("window.jianji.getState()")).project.mediaItems.length, 0, "management action keeps the current workspace untouched");
    assert.equal(await evaluate("document.querySelectorAll('.saved-collection-row > .button').length"), 0, "saved project actions are not duplicated beside the dropdown");
    await evaluate("document.querySelector('[aria-label=\"新的项目名称\"]').select()");
    await send("Input.insertText", { text: "重命名项目" });
    await click("确认重命名");
    await waitFor("document.body.innerText.includes('项目已重命名')");
    assert.equal(JSON.parse(await readFile(collectionFile, "utf8")).name, "重命名项目", "saved project rename is durable");
    assert.equal((await evaluate("window.jianji.getState()")).recentProjects[0].name, "重命名项目");
    await evaluate("document.querySelector('[aria-label=\"已保存的项目\"]').click()");
    await waitFor("[...document.querySelectorAll('.saved-collection-option-delete')].some(button => button.getAttribute('aria-label') === '删除项目 重命名项目')");
    await screenshot("saved-project-inline-management");
    await evaluate("[...document.querySelectorAll('.saved-collection-option-delete')].find(button => button.getAttribute('aria-label') === '删除项目 重命名项目').click()");
    await waitFor("document.body.innerText.includes('项目已移到系统回收站')");
    assert.equal((await evaluate("window.jianji.getState()")).recentProjects.length, 0, "deleted project leaves the saved list");
    assert.equal(await readFile(collectionFile + ".trashed", "utf8").then(() => true, () => false), true, "project file is moved to trash");
    assert.deepEqual(await readFile(source), sourceBytes, "deleting a project preserves the original video");
    assert.deepEqual(exceptions, []);
    console.log(JSON.stringify({ result: "PASS", scope: smokeScope, screenshotDirectory: directory, screenshot: path.join(directory, "saved-project-inline-management.png"), renamed: "重命名项目", deleted: true, sourcePreserved: true, runtimeExceptions: exceptions }, null, 2));
    break desktopSmoke;
  }
  await evaluate(`document.querySelector('[aria-label="已保存的项目"]').click(); document.querySelector('[data-recent-id=${JSON.stringify(savedEntry.id)}]').click()`);
  await waitFor(smokeScope === "saved-project-open" ? "document.querySelector('#creative-brief') !== null" : "document.body.innerText.includes('测试素材.mp4')");
  assert.equal((await evaluate("window.jianji.getState()")).project.mediaItems[0].probeStatus, "ready");
  assert.deepEqual(await readFile(source), sourceBytes, "naming and saving never change the source video");
  if (smokeScope === "saved-project-open") {
    assert.equal(await evaluate("document.querySelector('#creative-brief').value"), "恢复做到一半的提示", "saved project restores the unfinished brief");
    assert.equal(await evaluate("document.querySelector('#decoration-display-mode').value"), "first-5s", "saved project restores decoration timing");
    assert.equal(await evaluate("document.querySelector('#export-format').value"), "mov", "saved project restores export format");
    assert.equal(await evaluate("document.querySelector('#production-count').value"), "10", "saved project restores production count");
    assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent.includes('海盐蓝调'))?.getAttribute('aria-pressed')"), "true", "saved project restores the selected rule");
    assert.equal((await evaluate("window.jianji.getState()")).project.name, "夏季新品", "saved project restores its name");
    await evaluate("document.querySelector('#creative-brief').scrollIntoView({ block: 'center' })");
    await screenshot("saved-project-after-open");
    assert.deepEqual(exceptions, []);
    console.log(JSON.stringify({ result: "PASS", scope: smokeScope, screenshotDirectory: directory, before: path.join(directory, "saved-project-before-open.png"), after: path.join(directory, "saved-project-after-open.png"), projectName: "夏季新品", restoredStep: "templates", restoredBrief: "恢复做到一半的提示", restoredMedia: "测试素材.mp4" }, null, 2));
    break desktopSmoke;
  }
  await click("素材工作台");
  await evaluate("document.querySelector('[aria-label=\"项目名称\"]').focus(); document.querySelector('[aria-label=\"项目名称\"]').select()");
  await send("Input.insertText", { text: "尚未保存的新名称" });
  await waitFor("(async () => (await window.jianji.getState()).project.name === '尚未保存的新名称')()");
  assert.equal((await evaluate("window.jianji.getState()")).project.hasUnsavedChanges, true, "name edits participate in native quit and new/open protection");
  await click("规则模板");
  await click("素材工作台");
  assert.equal(await evaluate("document.querySelector('[aria-label=\"项目名称\"]').value"), "尚未保存的新名称", "navigation retains the edited collection name");
  await evaluate(`document.querySelector('[aria-label="已保存的项目"]').click(); document.querySelector('[data-recent-id=${JSON.stringify(savedEntry.id)}]').click()`);
  await waitFor("document.querySelector('[aria-label=\"已保存的项目\"]').getAttribute('aria-disabled') === 'false'");
  assert.equal((await evaluate("window.jianji.getState()")).project.name, "尚未保存的新名称", "cancelled open preserves unsaved names");
  await click("保存项目");
  await waitFor("document.body.innerText.includes('项目已保存')");
  assert.equal(JSON.parse(await readFile(collectionFile, "utf8")).name, "尚未保存的新名称", "topbar save uses the same collection name");
  const recentEntries = (await evaluate("window.jianji.getState()")).recentProjects;
  assert.equal(recentEntries.length, 1, "resaving a collection updates rather than duplicates its entry");
  assert.equal(recentEntries[0].name, "尚未保存的新名称");
  assert.equal(JSON.parse(await readFile(path.join(directory, "recent-projects.json"), "utf8")).entries[0].id, savedEntry.id, "saved collection index is persisted");
  await writeFile(path.join(directory, "index-failure"), "fail index writes only");
  await click("保存项目");
  await waitFor("document.body.innerText.includes('已保存项目列表暂时无法更新')");
  assert.equal((await evaluate("window.jianji.getState()")).project.hasUnsavedChanges, false, "index failure does not turn successful project save into failure");
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  await click("从项目文件导入");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  assert.equal(await evaluate("document.querySelector('[aria-label=\"项目名称\"]').value"), "尚未保存的新名称");
  assert.equal(await evaluate("document.body.innerText.includes('已保存项目列表暂时无法更新')"), true, "project open returns its actual state despite index write failure");
  await unlink(path.join(directory, "index-failure"));
  await click("保存项目");
  await waitFor("!document.body.innerText.includes('已保存项目列表暂时无法更新')");
  await screenshot("02-materials");
  await click("下一步");
  assert.equal(await evaluate("[...document.querySelectorAll('.corner-tabs button')].find(button => button.textContent === '全部交给 Agent').getAttribute('aria-pressed')"), "true", "price-only workflow defaults to automatic decoration");
  assert.equal(await evaluate("document.querySelectorAll('.template-card').length"), 0, "automatic decoration does not select a fixed template");
  assert.equal(await evaluate("document.body.innerText.includes('贴纸仅放四角且宽度 ≤ 10%')"), true, "automatic decoration shows the current sticker boundary");
  assert.equal(await evaluate("document.querySelector('#caption-font') === null && document.querySelector('option[value=\"text\"]') === null"), true, "no decorative text controls");
  await evaluate("document.querySelector('#product-price').focus()");
  await send("Input.insertText", { text: "19.9元30贴" });
  assert.equal(await evaluate("document.querySelector('#product-price').getAttribute('aria-invalid')"), "false");
  assert.equal(await evaluate("document.querySelector('#product-price').tagName"), "TEXTAREA");
  await evaluate("document.querySelector('#product-price').select()");
  await send("Input.insertText", { text: "春日新品" });
  await send("Input.dispatchKeyEvent", { type: "keyDown", key: "Enter", code: "Enter", windowsVirtualKeyCode: 13, text: "\r" });
  await send("Input.dispatchKeyEvent", { type: "keyUp", key: "Enter", code: "Enter", windowsVirtualKeyCode: 13 });
  await send("Input.insertText", { text: "到手30贴" });
  const twoLinePrice = "春日新品\n到手30贴";
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice);
  assert.equal(await evaluate("document.querySelector('#product-price').getAttribute('aria-invalid')"), "false");
  await click("保存项目");
  await waitFor("document.body.innerText.includes('项目已保存')");
  const priceProject = JSON.parse(await readFile(collectionFile, "utf8"));
  assert.equal(priceProject.templates.find(template => template.id === priceProject.activeTemplateId).productPriceDraft, twoLinePrice, "manual display text is stored in the active template JSON");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 0, "automatic decoration hides manual price choices");
  assert.equal(await evaluate("document.querySelector('.template-preview').textContent.includes('价格花字由 Agent 自主选择')"), true, "automatic preview marks its classic sample as undecided");
  const classicPreview = await evaluate("document.querySelector('.template-preview canvas').toDataURL()");
  await click("自己设置");
  assert.equal(await evaluate("document.querySelectorAll('.template-card').length"), 12, "manual decoration restores template choices");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 20, "manual decoration restores all twenty price choices");
  await click("森系奶绿");
  assert.equal(await evaluate("document.querySelector('[data-price-style=forest]').getAttribute('aria-pressed')"), "true");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice, "new styles preserve manual text");
  assert.notEqual(await evaluate("document.querySelector('.template-preview canvas').toDataURL()"), classicPreview, "new style redraws preview");
  await click("漫画撞色");
  assert.notEqual(await evaluate("document.querySelector('.template-preview canvas').toDataURL()"), classicPreview, "price selection redraws the preview");
  await click("海盐蓝调");
  assert.equal(await evaluate("document.querySelector('.price-style-option[aria-pressed=true]').textContent.includes('漫画撞色')"), true, "mode and template switches retain price style");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice, "style changes cannot rewrite price");
  await click("清爽日常");
  assert.deepEqual(await evaluate("[...document.querySelectorAll('.model-picker datalist option')].map(option => option.value)"), ["smoke-vision"], "saved candidates survive trailing slash and legacy default protocol");
  await evaluate("document.querySelector('.model-picker input').focus(); document.querySelector('.model-picker input').select()");
  await send("Input.insertText", { text: "smoke-vision-next" });
  await evaluate("document.querySelector('.effort-picker select').value = 'high'; document.querySelector('.effort-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await click("应用模型");
  await waitFor("document.body.innerText.includes('当前模型：smoke-vision-next')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-vision-next");
  await evaluate("document.querySelector('.model-picker').scrollIntoView()");
  await screenshot("02a-api-model");
  assert.equal(await evaluate("document.querySelector('.template-card.clean').getAttribute('aria-pressed')"), "true");
  await waitFor("document.body.innerText.includes('公主请下单（动效）') && document.body.innerText.includes('特别推荐')");
  assert.equal(await evaluate("document.querySelectorAll('.sticker-choices button').length"), 24);
  assert.equal(await evaluate("document.querySelectorAll('.sticker-choices img[src^=\"data:image/gif\"]').length"), 3);
  await click("公主请下单（动效）");
  assert.equal(await evaluate("[...document.querySelectorAll('.sticker-choices button')].find(button => button.textContent.includes('公主请下单')).getAttribute('aria-pressed')"), "true");
  await click("自动生成提示词");
  await waitFor("document.querySelector('.generate-brief').disabled && document.querySelector('#creative-brief').disabled");
  assert.equal(await evaluate("document.querySelector('.model-picker input').disabled"), true);
  assert.equal(await evaluate("document.querySelector('.effort-picker select').disabled"), true);
  assert.equal(await evaluate("(async () => { const state = await window.jianji.getState(); try { await window.jianji.selectModel({ connectionId: state.connections.selected, model: 'forbidden-switch' }); return false; } catch { return true; } })()"), true, "IPC rejects model switch during a request");
  await waitFor("document.querySelector('#creative-brief').value.includes('保持清爽自然')");
  assert.equal(briefRequests, 1, "one explicit API request");
  assert.equal(briefPayload.model, "smoke-vision-next", "selected model reaches provider request");
  assert.equal(briefPayload.reasoning_effort, "high", "selected effort reaches provider request");
  assert.equal(requests, 0, "prompt generation does not export");
  assert.equal(JSON.stringify(briefPayload).includes("公主请下单"), true, "selected sticker label sent");
  const generatedBrief = await evaluate("document.querySelector('#creative-brief').value");
  failBrief = true;
  await click("自动生成提示词");
  await waitFor("!document.querySelector('.generate-brief').disabled");
  assert.equal(await evaluate("document.querySelector('#creative-brief').value"), generatedBrief, "API error preserves existing text");
  assert.equal(briefRequests, 2, "no automatic retries");
  failBrief = false;
  await evaluate("document.querySelector('#creative-brief').focus();document.querySelector('#creative-brief').select()");
  await send("Input.insertText", { text: "生成后仍可编辑" });
  assert.equal(await evaluate("document.querySelector('#creative-brief').value"), "生成后仍可编辑");
  await screenshot("03-templates");
  await send("Emulation.setDeviceMetricsOverride", { width: 1080, height: 720, deviceScaleFactor: 1, mobile: false });
  assert.equal(await evaluate("document.documentElement.scrollWidth <= window.innerWidth"), true, "1080px viewport overflows");
  await screenshot("04-compact");
  await send("Emulation.clearDeviceMetricsOverride");
  await click("上传贴纸");
  await click("选择图片上传");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  const uploaded = (await evaluate("window.jianji.decorationCatalog()")).stickers.filter(sticker => sticker.source === "uploaded");
  assert.equal(uploaded.length, 1);
  await click("选择图片上传");
  await waitFor("!document.body.innerText.includes('正在上传…')");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.filter(sticker => sticker.source === "uploaded").length, 1);
  await screenshot("04a-sticker-library");
  await click("规则模板");
  await waitFor("document.querySelector('.sticker-choices button[aria-pressed=true]')?.textContent.includes('公主请下单')");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice, "library navigation preserves price and manual selection");
  assert.equal(await evaluate("[...document.querySelectorAll('main button')].some(button => button.textContent === '选择图片上传')"), false, "template picker no longer owns upload");
  await click(uploaded[0].label);
  await evaluate("document.querySelector('.cover-sticker-toggle input').click()");
  await waitFor("[...document.querySelectorAll('button')].some(button => button.textContent.includes('手动设置'))");
  await click("手动设置");
  await waitFor("document.querySelector('.cover-sticker-choice input') !== null");
  await evaluate("document.querySelector('.cover-sticker-choice input').click()");
  await waitFor("document.querySelector('.cover-sticker-frame') !== null");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent.includes('交给 Agent，制作')).disabled"), true, "unapplied cover edits block production");
  const dragCover = async (selector, dx, dy) => {
    const point = await evaluate(`(() => { const element = document.querySelector(${JSON.stringify(selector)}); element.scrollIntoView({block:'center'}); const r = element.getBoundingClientRect(); return { x:r.x+r.width/2, y:r.y+r.height/2 }; })()`);
    await send("Input.dispatchMouseEvent", { type: "mousePressed", ...point, button: "left", clickCount: 1 });
    await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: point.x + dx, y: point.y + dy, button: "left", buttons: 1 });
    await send("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x + dx, y: point.y + dy, button: "left", clickCount: 1 });
    await pause(80);
  };
  await dragCover('.cover-sticker-frame', -40, -20);
  await dragCover('.cover-sticker-handle', 30, 20);
  await click("保存覆盖设置");
  await waitFor("document.body.innerText.includes('覆盖设置已应用')");
  const coverState = await evaluate("window.jianji.getState()");
  const coverSettings = coverState.project.coverSticker;
  const coverRectangle = coverSettings.mediaRegions[coverState.project.mediaItems[0].id][0].rectangle;
  assert.ok(coverRectangle.x < 0.35 && coverRectangle.width > 0.3, "real pointer drag and resize update per-media IPC settings");
  assert.deepEqual(coverSettings.stickerIds, [uploaded[0].id]);
  await screenshot("04b-cover-sticker");
  await click("为此素材启用轨迹");
  const inputNumber = async (selector, value) => {
    await evaluate(`(() => { const input = document.querySelector(${JSON.stringify(selector)}); input.focus(); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, ${JSON.stringify(String(value))}); input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    await waitFor(`document.querySelector(${JSON.stringify(selector)}).value === ${JSON.stringify(String(value))}`);
    await waitFor("[...document.querySelectorAll('.cover-track-editor video')].every(video => !video.seeking)");
  };
  await inputNumber('.cover-track-time input[type=number]', 1000);
  await dragCover('.cover-sticker-frame', 50, 15);
  await dragCover('.cover-sticker-handle', 25, 15);
  await waitFor("document.querySelectorAll('.cover-keyframe-list > div').length === 2");
  await inputNumber('.cover-track-interval label:first-child input', 500);
  await inputNumber('.cover-track-interval label:last-child input', 2500);
  await inputNumber('.cover-track-time input[type=number]', 2500);
  assert.equal(await evaluate("document.querySelector('.cover-sticker-frame') === null"), true, "cover ends at the exclusive interval boundary");
  await inputNumber('.cover-track-time input[type=number]', 500);
  await waitFor("document.querySelector('.cover-sticker-frame') !== null");
  await click("保存覆盖设置");
  await waitFor("document.body.innerText.includes('覆盖设置已应用')");
  const motionState = await evaluate("window.jianji.getState()");
  const coverMediaId = motionState.project.mediaItems[0].id;
  const coverTrack = motionState.project.coverSticker.mediaRegions[coverMediaId][0].tracks[coverMediaId];
  assert.equal(coverTrack.keyframes.length, 2);
  assert.equal(coverTrack.keyframes[1].timeMs, 1000);
  assert.ok(coverTrack.keyframes[1].rectangle.x > coverTrack.keyframes[0].rectangle.x);
  assert.ok(coverTrack.keyframes[1].rectangle.width > coverTrack.keyframes[0].rectangle.width);
  const previewLeft = await evaluate("parseFloat(document.querySelector('.cover-sticker-frame').style.left) / 100");
  assert.ok(Math.abs(previewLeft - (coverTrack.keyframes[0].rectangle.x + coverTrack.keyframes[1].rectangle.x) / 2) < 0.0001, "preview interpolates halfway between keyframes");
  await screenshot("04c-cover-track");
  await evaluate("document.querySelector('.cover-track-preview video').play()");
  await waitFor("Number(document.querySelector('.cover-track-time input[type=number]').value) >= 800");
  await evaluate("document.querySelector('.cover-track-preview video').pause()");
  assert.equal(await evaluate("document.querySelectorAll('.cover-keyframe-list > div').length"), 2, "playback previews motion without recording extra keys");
  assert.ok(await evaluate(`parseFloat(document.querySelector('.cover-sticker-frame').style.left) / 100 > ${previewLeft}`), "playing video advances the cover preview");
  await unlink(uploadSource);
  await click("自动生成提示词");
  await waitFor("!document.querySelector('.generate-brief').disabled");
  assert.equal(briefRequests, 3);
  assert.equal(briefPayload.messages[1].content.filter(item => item.type === "image_url").length, 1, "brief generation sees the uploaded sticker image");
  assert.equal(JSON.stringify(briefPayload).includes(directory), false);
  await click("选择本地文件夹");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.completed') !== null");
  assert.equal(requests, 1);
  const state = await evaluate("window.jianji.getState()");
  const hardwareLabels = { h264_nvenc: "NVIDIA GPU", h264_amf: "AMD GPU", h264_qsv: "Intel GPU" };
  const capability = state.capabilities.videoEncoder;
  const expectedLabel = !capability ? "本地编码"
    : capability.kind === "hardware" ? hardwareLabels[capability.encoder]
    : "CPU 编码";
  assert.equal(await evaluate("document.querySelector('.engine-status').textContent"), `${expectedLabel} · ${state.capabilities.executionLimits.exports} 路`);
  assert.equal(state.queue.batches[0].batch.tasks[0].status, "completed");
  assert.equal(JSON.stringify(state).includes("local-smoke-key"), false);
  assert.equal(state.agentRun.items[0].summary, "保留主体与手动价格");
  const savedJob = JSON.parse(await readFile(path.join(directory, "jobs", `${state.queue.batches[0].batch.id}.json`), "utf8"));
  assert.equal(savedJob.batch.templateSnapshot.productPrice, twoLinePrice);
  const coverLayer = savedJob.batch.templateSnapshot.layers.find(layer => layer.cover);
  assert.equal(coverLayer.cover.stickerId, uploaded[0].id);
  assert.equal(coverLayer.x, coverRectangle.x);
  assert.equal(coverLayer.cover.height, coverRectangle.height);
  assert.deepEqual(coverLayer.cover.motion, coverTrack, "motion is frozen through real IPC and export");
  assert.deepEqual(savedJob.batch.templateSnapshot.layers.filter(layer => layer.type === "text").map(layer => layer.content), [twoLinePrice]);
  assert.equal(savedJob.batch.templateSnapshot.layers.some(layer => layer.type === "sticker" && layer.assetPath === path.join(directory, "uploaded-stickers", `${uploaded[0].id}.png`)), true, "uploaded image survives source removal and real FFmpeg export");
  assert.deepEqual(savedJob.batch.templateSnapshot.layers.find(layer => layer.type === "text").shadow, { color: { r: 232, g: 70, b: 120, a: 1 }, xRatio: 0.004, yRatio: 0.005 }, "selected price appearance survives IPC and is frozen for retries");
  await screenshot("05-results");
  await click("模型与 API");
  await click("API 连接管理");
  await evaluate("document.querySelector('details').open = true");
  await click("读取可导入配置");
  await waitFor("document.body.innerText.includes('MiniMax fixture')");
  assert.equal(await evaluate("document.body.innerText.includes('cc-switch-fixture-key')"), false);
  await screenshot("06-cc-switch");
  await click("导入到简辑");
  await waitFor("document.querySelectorAll('.provider-choice').length === 3");
  await click("删除");
  await click("确认删除");
  await waitFor("document.querySelectorAll('.provider-choice').length === 2");
  assert.equal((await evaluate("window.jianji.getState()")).connection.configured, false);
  await evaluate("[...document.querySelectorAll('.provider-choice')].find(p => p.querySelector('strong').textContent.includes('MiniMax') && p.textContent.includes('使用此连接')).querySelector('button').click()");
  await waitFor("document.body.innerText.includes('把视频拖到这里')");
  const imported = await evaluate("window.jianji.getState()");
  assert.equal(imported.connection.source, "api");
  assert.equal(imported.connection.protocol, "anthropic");
  assert.equal(JSON.stringify(imported).includes("cc-switch-fixture-key"), false);
  await click("规则模板");
  await waitFor("document.querySelector('.cover-sticker-choice input') !== null");
  await evaluate("document.querySelector('.cover-sticker-choice input').click(); document.querySelector('.cover-sticker-toggle input').click()");
  await click("保存覆盖设置");
  await waitFor("(async () => !(await window.jianji.getState()).project.coverSticker.enabled)()");
  await waitFor("document.querySelector('.cover-sticker-toggle input')?.checked === false");
  await evaluate("document.querySelector('.cover-sticker-toggle input').click()");
  await waitFor("document.querySelector('.cover-sticker-toggle input')?.checked === true");
  await waitFor("[...document.querySelectorAll('button')].find(button => button.textContent.includes('交给 Agent，制作')).disabled");
  await click("全部交给 Agent");
  assert.equal(await evaluate("document.querySelector('.cover-tracking-tabs button[aria-pressed=true]').textContent"), "手动设置", "decoration mode does not change tracking mode");
  await click("自己设置");
  assert.equal(await evaluate("document.querySelector('.cover-sticker-toggle input').checked"), true, "switching modes retains the unsaved manual cover draft");
  await click("全部交给 Agent");
  await evaluate("[...document.querySelectorAll('.cover-tracking-tabs button')].find(button => button.textContent.includes('Agent')).click()");
  await waitFor("document.querySelector('.cover-agent-status') !== null");
  assert.equal(await evaluate("document.querySelector('.cover-sticker-toggle input').checked"), true, "full Agent mode retains the independent cover switch");
  assert.equal(await evaluate("document.querySelector('.cover-tracking-tabs') !== null"), true, "tracking mode remains independent");
  assert.equal(await evaluate("document.querySelectorAll('.cover-sticker-choice input').length"), 0, "automatic cover selection does not require manual candidates");
  assert.equal(await evaluate("document.querySelector('.cover-track-editor') === null"), true, "automatic recognition needs no hand-drawn keys");
  await evaluate("document.querySelector('.cover-agent-mode').scrollIntoView({block:'center'})");
  await screenshot("06a-automatic-cover");
  await evaluate("(async () => { const state = await window.jianji.getState(); await window.jianji.selectVisionConnection({ connectionId: state.connections.selected, model: state.connection.model }); await window.jianji.selectReviewerConnection({ connectionId: state.connections.selected, model: state.connection.model }); })()");
  await click("保存覆盖设置");
  await waitFor("document.body.innerText.includes('覆盖设置已应用')");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent.includes('交给 Agent，制作')).disabled"), false, "automatic cover starts only after explicit settings are applied");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.failed') !== null");
  assert.equal(coverRequests, 3, "four seconds are scanned in three overlapping windows");
  const automaticState = await evaluate("window.jianji.getState()");
  const failedBatch = automaticState.queue.batches.find(entry => entry.batch.tasks.some(task => task.status === "failed"));
  const automaticJob = JSON.parse(await readFile(path.join(directory, "jobs", `${failedBatch.batch.id}.json`), "utf8"));
  assert.equal(automaticJob.batch.templateSnapshot.layers.filter(layer => layer.cover?.automatic).length, 2, "all recognized targets are frozen for retry");
  await writeFile(source, sourceBytes);
  await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent === '重试导出').click()");
  await waitFor("document.querySelector('.result-row .status-tag.running') !== null");
  const cancelAvailable = await evaluate("[...document.querySelectorAll('.result-row button')].some(button => button.textContent === '停止' && !button.disabled)");
  assert.equal(cancelAvailable, true, "Retry must leave cancellation available");
  await evaluate("[...document.querySelectorAll('.result-row button')].find(button => button.textContent === '停止').click()");
  await waitFor("document.querySelector('.result-row .status-tag.cancelled') !== null");
  assert.equal(await evaluate("document.querySelector('.result-row:has(.status-tag.cancelled)').innerText.includes('重试导出')"), false);
  assert.equal(requests, 2, "Export retry must not invoke the provider again");
  assert.equal(coverRequests, 3, "export retry reuses frozen automatic tracks");
  await waitFor("(async () => !(await window.jianji.getState()).project.hasUnsavedChanges)()");
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  const historicalProject = structuredClone(savedCollection);
  historicalProject.id = crypto.randomUUID();
  const historicalBatch = structuredClone(savedJob.batch);
  historicalBatch.id = crypto.randomUUID();
  historicalBatch.projectId = historicalProject.id;
  historicalBatch.status = "active";
  historicalBatch.tasks = Array.from({ length: 57 }, () => ({
    id: crypto.randomUUID(), batchId: historicalBatch.id, mediaId: historicalProject.mediaItems[0].id,
    status: "queued", progress: 0, attempt: 0, createdAt: new Date().toISOString(), attempts: [],
  }));
  historicalProject.exportBatches = [historicalBatch];
  await writeFile(collectionFile, JSON.stringify(historicalProject));
  await click("从项目文件导入");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  const reopened = await evaluate("window.jianji.getState()");
  assert.equal(reopened.queue.batches[0].batch.tasks.length, 57);
  assert.equal(reopened.queue.batches[0].batch.tasks.every(task => task.status === "interrupted"), true);
  await click("规则模板");
  await click("自己设置");
  await waitFor("document.querySelector('.model-picker input') && !document.querySelector('.model-picker input').disabled");
  assert.equal(await evaluate("[...document.querySelectorAll('.template-card')].every(button => !button.disabled)"), true, "abandoned queued jobs must not lock templates");
  assert.equal(await evaluate("document.querySelector('.model-picker input').disabled"), false, "abandoned jobs must not lock model selection");
  await click("清爽日常");
  assert.equal(await evaluate("document.querySelector('.template-card.clean').getAttribute('aria-pressed')"), "true");
  assert.equal(requests, 2, "opening a saved collection never restarts model work");
  assert.deepEqual(await readFile(source), sourceBytes, "recovery leaves the original video unchanged");
  await screenshot("07-reopened-collection-unlocked");
  await click("全部交给 Agent");
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await click("规则模板");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent === '全部交给 Agent').getAttribute('aria-pressed')"), "true", "library navigation preserves automatic mode");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 0, "automatic mode hides the retained manual price style");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), "", "the new collection ID does not inherit another collection's manual text");
  await evaluate("document.querySelector('#product-price').focus(); document.querySelector('#product-price').select()");
  await send("Input.insertText", { text: twoLinePrice });
  await evaluate("document.querySelector('.directory-picker').click()");
  await waitFor("[...document.querySelectorAll('button')].some(button => button.textContent.includes('交给 Agent，制作') && !button.disabled)");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.completed') !== null");
  assert.equal(shortlistRequests, 3, "one cover shortlist plus two automatic decoration shortlists");
  assert.equal(requests, 3);
  const autoState = await evaluate("window.jianji.getState()");
  const autoBatch = autoState.queue.batches.find(batch => batch.batch.tasks.some(task => task.status === "completed"));
  const autoJob = JSON.parse(await readFile(path.join(directory, "jobs", `${autoBatch.batch.id}.json`), "utf8"));
  assert.equal(autoJob.batch.templateSnapshot.layers.filter(layer => layer.type === "sticker" && !layer.cover).length, 4, "coverage-off automatic production fills four corners");
  assert.equal(autoJob.batch.templateSnapshot.layers.some(layer => layer.type === "sticker" && layer.assetPath.endsWith(`${uploaded[0].id}.png`)), true, "Agent-selected upload reaches real FFmpeg output");
  assert.deepEqual(autoJob.batch.templateSnapshot.layers.find(layer => layer.type === "text").color, { r: 224, g: 253, b: 255, a: 1 }, "Agent-selected price appearance reaches the frozen automatic export");
  if (smokeScope === "supervisor") {
    assert.ok(supervisorRequests >= 2, "recognition and actual preview supervision were exercised");
    await evaluate("document.querySelector('.result-row:has(.status-tag.completed)')?.scrollIntoView({ block: 'center' })");
    await screenshot("08-supervisor-completed");
    const report = { result: "PASS", scope: smokeScope, providerRequests: requests, coverRequests, supervisorRequests,
      screenshotDirectory: directory, output: autoBatch.batch.tasks[0].outputPath, runtimeExceptions: exceptions };
    assert.deepEqual(exceptions, []);
    await writeFile(path.join(directory, "supervisor-report.json"), JSON.stringify(report, null, 2));
    console.log(JSON.stringify(report, null, 2));
    break desktopSmoke;
  }
  const uploadedPath = path.join(directory, "uploaded-stickers", `${uploaded[0].id}.png`);
  const frozenStickerBytes = await readFile(uploadedPath);
  await click("规则模板");
  await click("自己设置");
  await click("左上角");
  await evaluate("document.querySelector('select[aria-label=\"角落内容类型\"]').value = 'sticker'; document.querySelector('select[aria-label=\"角落内容类型\"]').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor(`[...document.querySelectorAll('.sticker-choices button')].some(button => button.textContent === ${JSON.stringify(uploaded[0].label)})`);
  await click(uploaded[0].label);
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await evaluate("document.querySelector('.sticker-delete-actions button').click()");
  await click("取消");
  assert.equal(await evaluate("document.querySelectorAll('.uploaded-sticker-grid img').length"), 1, "cancel keeps the sticker");
  assert.equal(await evaluate("window.jianji.removeSticker('heart').then(() => false, () => true)"), true, "IPC cannot delete a builtin");
  await evaluate("document.querySelector('.sticker-delete-actions button').click()");
  await click("确认删除");
  await click("规则模板");
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await writeFile(path.join(directory, "delete.release"), "release");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 0");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.some(sticker => sticker.id === uploaded[0].id), false);
  assert.deepEqual(await readFile(uploadedPath), frozenStickerBytes, "deletion preserves the frozen asset for export retries");
  assert.equal(await evaluate(`window.jianji.generateBrief({ruleId:'clean',decorations:{mode:'manual',sticker:${JSON.stringify(uploaded[0].id)},productPrice:'19.90'}}).then(() => false, () => true)`), true, "deleted upload cannot reach a new model request");
  assert.equal(briefRequests, 3);
  await click("规则模板");
  assert.equal(await evaluate("document.querySelector('select[aria-label=\"角落内容类型\"]').value"), "none", "deleting clears explicit corner selection");
  await click("默认样式");
  await waitFor("document.querySelector('.sticker-choices button[aria-pressed=true]')?.textContent === '不加贴纸'");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice);
  await writeFile(uploadSource, frozenStickerBytes);
  await click("上传贴纸");
  await click("选择图片上传");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.some(sticker => sticker.id === uploaded[0].id), true, "reimport restores a removed upload");
  await screenshot("08-sticker-delete-restored");
  await waitFor("(async () => !(await window.jianji.getState()).project.hasUnsavedChanges)()");
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  await click("素材工作台");
  const managedEntry = (await evaluate("window.jianji.getState()")).recentProjects[0];
  const managementProjectId = (await evaluate("window.jianji.getState()")).project.id;
  await evaluate(`document.querySelector('[aria-label="已保存的项目"]').click(); document.querySelector('[aria-label=${JSON.stringify(`重命名项目 ${managedEntry.name}`)}]').click()`);
  assert.equal((await evaluate("window.jianji.getState()")).project.id, managementProjectId, "renaming a saved project does not load it");
  assert.equal(await evaluate("document.querySelectorAll('.saved-collection-row > .button').length"), 0, "saved project actions are not duplicated beside the dropdown");
  await evaluate("document.querySelector('[aria-label=\"新的项目名称\"]').select()");
  await send("Input.insertText", { text: "重命名项目" });
  await click("确认重命名");
  await waitFor("document.body.innerText.includes('项目已重命名')");
  assert.equal(JSON.parse(await readFile(collectionFile, "utf8")).name, "重命名项目", "saved collection rename is durable");
  assert.equal((await evaluate("window.jianji.getState()")).recentProjects[0].name, "重命名项目");
  await evaluate("document.querySelector('[aria-label=\"已保存的项目\"]').click()");
  await waitFor("[...document.querySelectorAll('.saved-collection-option-delete')].some(button => button.getAttribute('aria-label') === '删除项目 重命名项目')");
  await screenshot("09-saved-collection-list-delete");
  await evaluate("[...document.querySelectorAll('.saved-collection-option-delete')].find(button => button.getAttribute('aria-label') === '删除项目 重命名项目').click()");
  await waitFor("document.body.innerText.includes('项目已移到系统回收站')");
  assert.equal((await evaluate("window.jianji.getState()")).recentProjects.length, 0, "deleted collection leaves the saved list");
  assert.equal((await evaluate("window.jianji.getState()")).project.id, managementProjectId, "deleting a saved project does not load it");
  assert.equal(await readFile(collectionFile + ".trashed", "utf8").then(() => true, () => false), true, "project file is moved to trash");
  assert.deepEqual(await readFile(source), sourceBytes, "deleting a collection preserves the original video");
  assert.deepEqual(exceptions, []);
  const codexPid = Number(await readFile(path.join(directory, "codex.pid"), "utf8"));
  const exit = new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("Application did not finish shutdown")), 10_000);
    child.once("exit", (code) => { clearTimeout(timer); resolve(code); });
  });
  await writeFile(path.join(directory, "index-failure"), "fail index writes only");
  await evaluate("window.jianji.renameProject('退出保存测试')");
  await writeFile(path.join(directory, "quit.signal"), "quit");
  assert.equal(await exit, 0);
  assert.throws(() => process.kill(codexPid, 0), { code: "ESRCH" }, "App must wait for its Codex child to exit");
  console.log(JSON.stringify({ result: "PASS", providerRequests: requests, briefRequests, shortlistRequests, coverRequests, supervisorRequests, screenshotDirectory: directory, output: state.queue.batches[0].batch.tasks[0].outputPath, runtimeExceptions: exceptions }, null, 2));
} catch (error) {
  console.error(processLog.slice(-3000));
  throw error;
} finally {
  socket?.close();
  child.kill("SIGKILL");
  try {
    const pid = Number(await readFile(path.join(directory, "codex.pid"), "utf8"));
    if (Number.isSafeInteger(pid) && pid > 0) {
      const owned = process.platform !== "linux" || (await readFile(`/proc/${pid}/cmdline`, "utf8")).includes(path.join(root, "tests/fixtures/codex-app-server.cjs"));
      if (owned) process.kill(pid, "SIGKILL");
    }
  } catch { /* The task-owned fixture has already exited. */ }
  server.closeAllConnections();
  await new Promise((resolve) => server.close(resolve));
}
