import assert from "node:assert/strict";
import { spawn, execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createServer } from "node:http";
import { createServer as createSocketServer } from "node:net";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

// Real Electron/IPC/FFmpeg smoke; only the provider and native file picker are fixtures.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const directory = await mkdtemp(path.join(tmpdir(), "jianji-desktop-smoke-"));
const source = path.join(directory, "测试素材.mp4");
const output = path.join(directory, "output");
const collectionFile = path.join(directory, "夏季新品.jianji-project.json");
execFileSync(process.env.JIANJI_FFMPEG_PATH || "ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", "testsrc=size=1280x720:rate=24", "-t", "4", "-c:v", "libx264", "-pix_fmt", "yuv420p", source]);
const sourceBytes = await readFile(source);
const uploadSource = path.join(directory, "uploaded-heart.png");
execFileSync(process.env.JIANJI_FFMPEG_PATH || "ffmpeg", ["-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", "color=c=red:s=64x64", "-frames:v", "1", uploadSource]);
let requests = 0;
let briefRequests = 0;
let shortlistRequests = 0;
let briefPayload;
let failBrief = false;
const server = createServer((request, response) => {
  let body = "";
  request.on("data", (chunk) => { body += chunk; });
  request.on("end", async () => {
    const input = JSON.parse(body);
    const anthropic = request.url === "/anthropic/v1/messages";
    assert.equal(request.url, anthropic ? "/anthropic/v1/messages" : "/v1/chat/completions");
    const userContent = input.messages[anthropic ? 0 : 1].content;
    const systemText = anthropic ? input.system : input.messages[0].content;
    if (systemText.includes("你是视频贴纸选材师")) {
      shortlistRequests += 1;
      const uploadText = userContent.find(item => item.type === "text" && item.text.includes("用户上传贴纸，目录编号"))?.text;
      assert.ok(uploadText, "automatic shortlist receives uploaded artwork with its catalog number");
      assert.equal(userContent.filter(item => item.type === (anthropic ? "image" : "image_url")).length, 4);
      const number = Number(uploadText.match(/目录编号 (\d+)/)[1]);
      const text = JSON.stringify({ candidates: [number] });
      response.setHeader("Content-Type", "application/json");
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    if (typeof userContent === "string" || systemText.includes("你是视频包装创意总监")) {
      assert.equal(request.headers.authorization, anthropic ? "Bearer cc-switch-fixture-key" : "Bearer local-smoke-key");
      briefRequests += 1; briefPayload = input;
      await new Promise(resolve => setTimeout(resolve, 300));
      response.setHeader("Content-Type", "application/json");
      if (failBrief) { response.writeHead(503); response.end('{}'); return; }
      const text = "保持清爽自然，保留已选贴纸与手动价格，按画面需要留白。";
      response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
      return;
    }
    assert.equal(input.messages[anthropic ? 0 : 1].content.filter((item) => item.type === (anthropic ? "image" : "image_url")).length, 4, "three video frames plus the actual uploaded sticker image");
    assert.equal(JSON.stringify(input).includes("用户手动选择的上传贴纸") || JSON.stringify(input).includes("贴纸候选"), true);
    assert.equal(JSON.stringify(input).includes(directory), false, "local upload paths never reach the provider");
    assert.equal(input.model, anthropic ? "MiniMax-M3" : "smoke-vision-next", "video analysis uses the selected model");
    if (!anthropic) assert.equal(input.reasoning_effort, "high", "video analysis uses selected effort");
    assert.equal(request.headers.authorization, anthropic ? "Bearer cc-switch-fixture-key" : "Bearer local-smoke-key");
    requests += 1;
    if (requests === 2) await unlink(source); // Repro a local render failure after analysis.
    response.setHeader("Content-Type", "application/json");
    const automatic = systemText.includes('"stickers"');
    const text = JSON.stringify({ summary: "保留主体与手动价格", captions: [], ...(automatic ? { stickers: [{ corner: "top-left", sticker: JSON.stringify(userContent).match(/uploaded-[a-f0-9]{64}/)[0], width: 0.12, rotationDeg: 0 }], priceStyle: "ice" } : {}), filter: "cool", intensity: 0.3 });
    response.end(JSON.stringify(anthropic ? { content: [{ type: "text", text }] } : { choices: [{ message: { content: text } }] }));
  });
});
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const apiPort = server.address().port;
const fixtureHome = path.join(directory, "home");
await mkdir(path.join(fixtureHome, ".cc-switch"), { recursive: true });
const SQL = await require("sql.js/dist/sql-asm.js")();
const db = new SQL.Database();
db.run("CREATE TABLE providers (id TEXT, app_type TEXT, name TEXT, settings_config TEXT, is_current INTEGER)");
db.run("INSERT INTO providers VALUES (?, ?, ?, ?, 1)", ["fixture", "claude", "MiniMax fixture", JSON.stringify({ env: { ANTHROPIC_AUTH_TOKEN: "cc-switch-fixture-key", ANTHROPIC_BASE_URL: `http://127.0.0.1:${apiPort}/anthropic`, ANTHROPIC_MODEL: "MiniMax-M3" } })]);
await writeFile(path.join(fixtureHome, ".cc-switch", "cc-switch.db"), Buffer.from(db.export())); db.close();
const portServer = createSocketServer();
await new Promise((resolve) => portServer.listen(0, "127.0.0.1", resolve));
const debugPort = portServer.address().port;
await new Promise((resolve) => portServer.close(resolve));
const bootstrap = path.join(directory, "bootstrap.cjs");
await writeFile(path.join(directory, "recent-projects.json"), "{broken-index-fixture");
await writeFile(bootstrap, `const { app, dialog, shell } = require("electron");
process.chdir(${JSON.stringify(directory)});
app.setPath("documents", ${JSON.stringify(directory)});
const filePromises = require("node:fs/promises");
const originalWriteFile = filePromises.writeFile;
filePromises.writeFile = async (file, ...args) => {
  if (typeof file === "string" && file.includes("recent-projects.json.tmp-") && require("node:fs").existsSync(${JSON.stringify(path.join(directory, "index-failure"))})) throw new Error("ENOSPC: fixture recent index failure");
  if (typeof file === "string" && file.endsWith(".deleted")) {
    while (!require("node:fs").existsSync(${JSON.stringify(path.join(directory, "delete.release"))})) await new Promise(resolve => setTimeout(resolve, 10));
  }
  return originalWriteFile(file, ...args);
};
require("node:os").homedir = () => ${JSON.stringify(fixtureHome)};
const childProcess = require("node:child_process");
const nativeSpawn = childProcess.spawn;
childProcess.spawn = (command, args, options) => /[\\\\/]vendor[\\\\/].*[\\\\/]bin[\\\\/]codex(?:\\.exe)?$/.test(command) ? nativeSpawn(${JSON.stringify(process.execPath)}, [${JSON.stringify(path.join(root, "tests/fixtures/codex-app-server.cjs"))}, ${JSON.stringify(path.join(directory, "codex.pid"))}], options) : nativeSpawn(command, args, options);
shell.openExternal = async (url) => { if (!url.startsWith("https://auth.openai.com/")) throw new Error("Unexpected login URL"); };
app.setPath("userData", ${JSON.stringify(directory)});
require("node:fs").watch(${JSON.stringify(directory)}, (_event, name) => { if (name === "quit.signal") app.quit(); });
app.getAppPath = () => ${JSON.stringify(root)};
app.commandLine.appendSwitch("remote-debugging-port", ${JSON.stringify(String(debugPort))});
app.commandLine.appendSwitch("remote-debugging-address", "127.0.0.1");
let stickerPickerCalls = 0;
dialog.showOpenDialog = async (_window, options) => {
  if (options.title === "上传贴纸") {
    stickerPickerCalls += 1;
    return stickerPickerCalls === 1 ? { canceled: true, filePaths: [] } : { canceled: false, filePaths: [stickerPickerCalls === 2 ? ${JSON.stringify(source)} : ${JSON.stringify(uploadSource)}] };
  }
  return { canceled: false, filePaths: options.properties.includes("openDirectory") ? [${JSON.stringify(output)}] : options.title === "打开项目" ? [${JSON.stringify(collectionFile)}] : [${JSON.stringify(source)}] };
};
dialog.showSaveDialog = async () => ({ canceled: false, filePath: ${JSON.stringify(collectionFile)} });
dialog.showMessageBox = async (_window, options) => ({ response: options.title === "保存项目更改？" && require("node:fs").existsSync(${JSON.stringify(path.join(directory, "index-failure"))}) ? 0 : 1 });
require(${JSON.stringify(path.join(root, "dist-electron/main.cjs"))});
`);
const environment = { ...process.env };
delete environment.ELECTRON_RUN_AS_NODE;
delete environment.JIANJI_DEV_SERVER_URL;
const child = spawn(require("electron"), [bootstrap], { cwd: root, env: environment, stdio: ["ignore", "pipe", "pipe"] });
let processLog = "";
child.stderr.on("data", (chunk) => { processLog += chunk.toString(); });
child.stdout.on("data", (chunk) => { processLog += chunk.toString(); });
const pause = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
let socket;
try {
  let target;
  for (let attempt = 0; attempt < 100; attempt++) {
    if (child.exitCode !== null) throw new Error(`Electron exited: ${processLog}`);
    try { target = (await (await fetch(`http://127.0.0.1:${debugPort}/json`)).json()).find((page) => page.type === "page"); } catch {}
    if (target) break;
    await pause(100);
  }
  assert.ok(target, processLog);
  socket = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener("open", resolve, { once: true }); socket.addEventListener("error", reject, { once: true }); });
  let sequence = 0;
  const pending = new Map();
  const exceptions = [];
  socket.addEventListener("message", (event) => {
    const message = JSON.parse(event.data);
    if (message.method === "Runtime.exceptionThrown") exceptions.push(message.params.exceptionDetails.text);
    if (message.id) {
      const entry = pending.get(message.id); pending.delete(message.id);
      if (message.error) entry?.reject(new Error(JSON.stringify(message.error)));
      else entry?.resolve(message.result);
    }
  });
  const send = (method, params = {}) => new Promise((resolve, reject) => {
    const id = ++sequence;
    const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP timeout: ${method}`)); }, 15_000);
    pending.set(id, { resolve: (value) => { clearTimeout(timer); resolve(value); }, reject: (error) => { clearTimeout(timer); reject(error); } });
    socket.send(JSON.stringify({ id, method, params }));
  });
  const evaluate = async (expression) => {
    const result = await send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true });
    if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
    return result.result.value;
  };
  const waitFor = async (expression) => {
    for (let attempt = 0; attempt < 200; attempt++) { if (await evaluate(expression)) return; await pause(100); }
    throw new Error(`Timed out: ${expression}`);
  };
  const click = async (text) => {
    const selector = `[...document.querySelectorAll('button')].find(button => button.textContent.includes(${JSON.stringify(text)}))`;
    assert.equal(await evaluate(`Boolean(${selector} && !${selector}.disabled)`), true, `Button unavailable: ${text}`);
    await evaluate(`${selector}.click()`);
    await pause(80);
  };
  const screenshot = async (name) => {
    await send("Page.bringToFront");
    const image = await send("Page.captureScreenshot", { format: "png" });
    await writeFile(path.join(directory, `${name}.png`), Buffer.from(image.data, "base64"));
  };
  await send("Runtime.enable");
  await waitFor("document.body.innerText.includes('接入你的创作搭档')");
  assert.equal(await evaluate("document.body.innerText.includes('素材集列表暂时无法读取')"), true, "a corrupt index must not prevent desktop startup");
  await click("上传贴纸");
  await waitFor("document.body.innerText.includes('还没有上传贴纸')");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].some(button => button.textContent === '选择图片上传' && !button.disabled)"), true, "standalone sticker library is available without a model or video");
  await screenshot("00-sticker-library-empty");
  await click("选择图片上传");
  await waitFor("!document.body.innerText.includes('正在上传…')");
  assert.equal(await evaluate("document.querySelectorAll('.uploaded-sticker-grid img').length"), 0, "cancel preserves empty library");
  await click("选择图片上传");
  await waitFor("document.querySelector('[role=alert]')?.textContent.includes('上传失败')");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].some(button => button.textContent === '选择图片上传' && !button.disabled)"), true, "invalid upload can be retried");
  await click("模型与 API");
  const duplicate = spawn(require("electron"), [bootstrap], { cwd: root, env: environment, stdio: "ignore" });
  const duplicateExit = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => { duplicate.kill(); reject(new Error("Second instance failed to exit")); }, 5000);
    duplicate.once("exit", (code) => { clearTimeout(timeout); resolve(code); });
  });
  assert.equal(duplicateExit, 0, "Second instance must leave the existing connection owner running");
  await screenshot("01-connection");
  await click("使用 ChatGPT 登录");
  await waitFor("document.body.innerText.includes('取消登录')");
  await screenshot("01a-login-pending");
  await click("取消登录");
  await waitFor("document.body.innerText.includes('使用 ChatGPT 登录')");
  await click("使用 ChatGPT 登录");
  await waitFor("document.body.innerText.includes('smoke@example.test')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.source, "chatgpt");
  assert.deepEqual(await evaluate("[...document.querySelector('.model-picker select').options].map(option => option.value)"), ["", "smoke-codex-vision", "smoke-codex-next"]);
  await evaluate("document.querySelector('.model-picker select').value = 'smoke-codex-next'; document.querySelector('.model-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor("document.body.innerText.includes('创作模型已切换并保存')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-codex-next");
  assert.deepEqual(await evaluate("[...document.querySelector('.effort-picker select').options].map(option => option.value)"), ["", "medium", "xhigh", "ultra"], "efforts come from the chosen model");
  await evaluate("document.querySelector('.effort-picker select').value = 'xhigh'; document.querySelector('.effort-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor("document.querySelector('.effort-picker select').value === 'xhigh' && !document.querySelector('.effort-picker select').disabled");
  assert.equal((await evaluate("window.jianji.getState()")).connection.reasoningEffort, "xhigh");
  await click("刷新登录状态");
  assert.equal((await evaluate("window.jianji.getState()")).chatgpt.status, "ready");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-codex-next");
  assert.equal(JSON.parse(await readFile(path.join(directory, "connections/connections.json"), "utf8")).chatgptModel, "smoke-codex-next");
  assert.equal(JSON.parse(await readFile(path.join(directory, "connections/connections.json"), "utf8")).chatgptReasoningEffort, "xhigh");
  await screenshot("01b-chatgpt-ready");
  await click("断开");
  await waitFor("document.body.innerText.includes('使用 ChatGPT 登录')");
  await click("API 连接管理");
  await click("添加 API 连接");
  for (const [index, value] of ["Smoke API", `http://127.0.0.1:${apiPort}/v1/`, "smoke-vision", "local-smoke-key"].entries()) {
    await evaluate(`document.querySelectorAll('.connection-form input')[${index}].focus();document.querySelectorAll('.connection-form input')[${index}].select()`);
    await send("Input.insertText", { text: value });
  }
  await click("保存连接");
  await waitFor("document.body.innerText.includes('使用此连接')");
  await click("编辑");
  assert.equal(await evaluate("document.querySelector('input[type=password]').value"), "");
  await click("保存连接");
  await click("使用此连接");
  await waitFor("document.body.innerText.includes('把视频拖到这里')");
  await evaluate("(async () => { const state = await window.jianji.getState(); const { protocol, ...profile } = state.connections.profiles[0]; await window.jianji.saveConnection(profile); })()");
  assert.equal(await evaluate("localStorage.length"), 0);
  await click("选择本地素材");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  await evaluate("document.querySelector('[aria-label=\"素材集名称\"]').focus(); document.querySelector('[aria-label=\"素材集名称\"]').select()");
  await send("Input.insertText", { text: "夏季新品" });
  await click("保存素材集");
  await waitFor("document.body.innerText.includes('素材集已保存')");
  const savedCollection = JSON.parse(await readFile(collectionFile, "utf8"));
  assert.equal(savedCollection.name, "夏季新品");
  assert.equal(savedCollection.mediaItems[0].displayName, "测试素材.mp4");
  assert.equal(savedCollection.mediaItems[0].sourcePath, source);
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  const savedEntry = (await evaluate("window.jianji.getState()")).recentProjects.find(entry => entry.name === "夏季新品");
  assert.ok(savedEntry, "saved collection appears in the dropdown");
  await evaluate(`document.querySelector('[aria-label="已保存的素材集"]').value = ${JSON.stringify(savedEntry.id)}; document.querySelector('[aria-label="已保存的素材集"]').dispatchEvent(new Event('change', { bubbles: true }))`);
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  assert.equal(await evaluate("document.querySelector('[aria-label=\"素材集名称\"]').value"), "夏季新品");
  assert.equal((await evaluate("window.jianji.getState()")).project.mediaItems[0].probeStatus, "ready");
  assert.deepEqual(await readFile(source), sourceBytes, "naming and saving never change the source video");
  await evaluate("document.querySelector('[aria-label=\"素材集名称\"]').focus(); document.querySelector('[aria-label=\"素材集名称\"]').select()");
  await send("Input.insertText", { text: "尚未保存的新名称" });
  await waitFor("(async () => (await window.jianji.getState()).project.name === '尚未保存的新名称')()");
  assert.equal((await evaluate("window.jianji.getState()")).project.hasUnsavedChanges, true, "name edits participate in native quit and new/open protection");
  await click("规则模板");
  await click("素材工作台");
  assert.equal(await evaluate("document.querySelector('[aria-label=\"素材集名称\"]').value"), "尚未保存的新名称", "navigation retains the edited collection name");
  await evaluate(`document.querySelector('[aria-label="已保存的素材集"]').value = ${JSON.stringify(savedEntry.id)}; document.querySelector('[aria-label="已保存的素材集"]').dispatchEvent(new Event('change', { bubbles: true }))`);
  await waitFor("!document.querySelector('[aria-label=\"已保存的素材集\"]').disabled");
  assert.equal((await evaluate("window.jianji.getState()")).project.name, "尚未保存的新名称", "cancelled open preserves unsaved names");
  await click("保存项目");
  await waitFor("document.body.innerText.includes('素材集已保存')");
  assert.equal(JSON.parse(await readFile(collectionFile, "utf8")).name, "尚未保存的新名称", "topbar save uses the same collection name");
  const recentEntries = (await evaluate("window.jianji.getState()")).recentProjects;
  assert.equal(recentEntries.length, 1, "resaving a collection updates rather than duplicates its entry");
  assert.equal(recentEntries[0].name, "尚未保存的新名称");
  assert.equal(JSON.parse(await readFile(path.join(directory, "recent-projects.json"), "utf8")).entries[0].id, savedEntry.id, "dropdown index is persisted");
  await writeFile(path.join(directory, "index-failure"), "fail index writes only");
  await click("保存素材集");
  await waitFor("document.body.innerText.includes('素材集列表暂时无法更新')");
  assert.equal((await evaluate("window.jianji.getState()")).project.hasUnsavedChanges, false, "index failure does not turn successful project save into failure");
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  await click("打开其他素材集");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  assert.equal(await evaluate("document.querySelector('[aria-label=\"素材集名称\"]').value"), "尚未保存的新名称");
  assert.equal(await evaluate("document.body.innerText.includes('素材集列表暂时无法更新')"), true, "project open returns its actual state despite index write failure");
  await unlink(path.join(directory, "index-failure"));
  await click("保存素材集");
  await waitFor("!document.body.innerText.includes('素材集列表暂时无法更新')");
  await screenshot("02-materials");
  await click("下一步");
  assert.equal(await evaluate("[...document.querySelectorAll('.corner-tabs button')].find(button => button.textContent === '全部交给 Agent').getAttribute('aria-pressed')"), "true", "price-only workflow defaults to automatic decoration");
  assert.equal(await evaluate("document.querySelectorAll('.template-card').length"), 0, "automatic decoration does not select a fixed template");
  assert.equal(await evaluate("document.body.innerText.includes('贴纸仅放四角且宽度 ≤ 20%')"), true, "automatic decoration shows neutral sticker boundary");
  assert.equal(await evaluate("document.querySelector('#caption-font') === null && document.querySelector('option[value=\"text\"]') === null"), true, "no decorative text controls");
  await evaluate("document.querySelector('#product-price').focus()");
  await send("Input.insertText", { text: "19.9元30贴" });
  assert.equal(await evaluate("document.querySelector('#product-price').getAttribute('aria-invalid')"), "false");
  assert.equal(await evaluate("document.querySelector('#product-price').tagName"), "TEXTAREA");
  await evaluate("document.querySelector('#product-price').select()");
  await send("Input.insertText", { text: "春日新品" });
  await send("Input.dispatchKeyEvent", { type: "keyDown", key: "Enter", code: "Enter", windowsVirtualKeyCode: 13, text: "\r" });
  await send("Input.dispatchKeyEvent", { type: "keyUp", key: "Enter", code: "Enter", windowsVirtualKeyCode: 13 });
  await send("Input.insertText", { text: "到手30贴" });
  const twoLinePrice = "春日新品\n到手30贴";
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice);
  assert.equal(await evaluate("document.querySelector('#product-price').getAttribute('aria-invalid')"), "false");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 0, "automatic decoration hides manual price choices");
  assert.equal(await evaluate("document.querySelector('.template-preview').textContent.includes('价格花字由 Agent 自主选择')"), true, "automatic preview marks its classic sample as undecided");
  const classicPreview = await evaluate("document.querySelector('.template-preview canvas').toDataURL()");
  await click("自己设置");
  assert.equal(await evaluate("document.querySelectorAll('.template-card').length"), 12, "manual decoration restores template choices");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 8, "manual decoration restores eight price choices");
  await click("漫画撞色");
  assert.notEqual(await evaluate("document.querySelector('.template-preview canvas').toDataURL()"), classicPreview, "price selection redraws the preview");
  await click("海盐蓝调");
  assert.equal(await evaluate("document.querySelector('.price-style-option[aria-pressed=true]').textContent.includes('漫画撞色')"), true, "mode and template switches retain price style");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice, "style changes cannot rewrite price");
  await click("清爽日常");
  assert.deepEqual(await evaluate("[...document.querySelectorAll('.model-picker datalist option')].map(option => option.value)"), ["smoke-vision"], "saved candidates survive trailing slash and legacy default protocol");
  await evaluate("document.querySelector('.model-picker input').focus(); document.querySelector('.model-picker input').select()");
  await send("Input.insertText", { text: "smoke-vision-next" });
  await evaluate("document.querySelector('.effort-picker select').value = 'high'; document.querySelector('.effort-picker select').dispatchEvent(new Event('change', { bubbles: true }))");
  await click("应用模型");
  await waitFor("document.body.innerText.includes('当前模型：smoke-vision-next')");
  assert.equal((await evaluate("window.jianji.getState()")).connection.model, "smoke-vision-next");
  await evaluate("document.querySelector('.model-picker').scrollIntoView()");
  await screenshot("02a-api-model");
  assert.equal(await evaluate("document.querySelector('.template-card.clean').getAttribute('aria-pressed')"), "true");
  await waitFor("document.body.innerText.includes('公主请下单（动效）') && document.body.innerText.includes('特别推荐')");
  assert.equal(await evaluate("document.querySelectorAll('.sticker-choices button').length"), 24);
  assert.equal(await evaluate("document.querySelectorAll('.sticker-choices img[src^=\"data:image/gif\"]').length"), 3);
  await click("公主请下单（动效）");
  assert.equal(await evaluate("[...document.querySelectorAll('.sticker-choices button')].find(button => button.textContent.includes('公主请下单')).getAttribute('aria-pressed')"), "true");
  await click("自动生成提示词");
  await waitFor("document.querySelector('.generate-brief').disabled && document.querySelector('#creative-brief').disabled");
  assert.equal(await evaluate("document.querySelector('.model-picker input').disabled"), true);
  assert.equal(await evaluate("document.querySelector('.effort-picker select').disabled"), true);
  assert.equal(await evaluate("(async () => { const state = await window.jianji.getState(); try { await window.jianji.selectModel({ connectionId: state.connections.selected, model: 'forbidden-switch' }); return false; } catch { return true; } })()"), true, "IPC rejects model switch during a request");
  await waitFor("document.querySelector('#creative-brief').value.includes('保持清爽自然')");
  assert.equal(briefRequests, 1, "one explicit API request");
  assert.equal(briefPayload.model, "smoke-vision-next", "selected model reaches provider request");
  assert.equal(briefPayload.reasoning_effort, "high", "selected effort reaches provider request");
  assert.equal(requests, 0, "prompt generation does not export");
  assert.equal(JSON.stringify(briefPayload).includes("公主请下单"), true, "selected sticker label sent");
  const generatedBrief = await evaluate("document.querySelector('#creative-brief').value");
  failBrief = true;
  await click("自动生成提示词");
  await waitFor("!document.querySelector('.generate-brief').disabled");
  assert.equal(await evaluate("document.querySelector('#creative-brief').value"), generatedBrief, "API error preserves existing text");
  assert.equal(briefRequests, 2, "no automatic retries");
  failBrief = false;
  await evaluate("document.querySelector('#creative-brief').focus();document.querySelector('#creative-brief').select()");
  await send("Input.insertText", { text: "生成后仍可编辑" });
  assert.equal(await evaluate("document.querySelector('#creative-brief').value"), "生成后仍可编辑");
  await screenshot("03-templates");
  await send("Emulation.setDeviceMetricsOverride", { width: 1080, height: 720, deviceScaleFactor: 1, mobile: false });
  assert.equal(await evaluate("document.documentElement.scrollWidth <= window.innerWidth"), true, "1080px viewport overflows");
  await screenshot("04-compact");
  await send("Emulation.clearDeviceMetricsOverride");
  await click("上传贴纸");
  await click("选择图片上传");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  const uploaded = (await evaluate("window.jianji.decorationCatalog()")).stickers.filter(sticker => sticker.source === "uploaded");
  assert.equal(uploaded.length, 1);
  await click("选择图片上传");
  await waitFor("!document.body.innerText.includes('正在上传…')");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.filter(sticker => sticker.source === "uploaded").length, 1);
  await screenshot("04a-sticker-library");
  await click("规则模板");
  await waitFor("document.querySelector('.sticker-choices button[aria-pressed=true]')?.textContent.includes('公主请下单')");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice, "library navigation preserves price and manual selection");
  assert.equal(await evaluate("[...document.querySelectorAll('main button')].some(button => button.textContent === '选择图片上传')"), false, "template picker no longer owns upload");
  await click(uploaded[0].label);
  await evaluate("document.querySelector('.cover-sticker-toggle input').click(); document.querySelector('.cover-sticker-choice input').click()");
  await waitFor("document.querySelector('.cover-sticker-frame') !== null");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent.includes('交给 Agent，制作')).disabled"), true, "unapplied cover edits block production");
  const dragCover = async (selector, dx, dy) => {
    const point = await evaluate(`(() => { const element = document.querySelector(${JSON.stringify(selector)}); element.scrollIntoView({block:'center'}); const r = element.getBoundingClientRect(); return { x:r.x+r.width/2, y:r.y+r.height/2 }; })()`);
    await send("Input.dispatchMouseEvent", { type: "mousePressed", ...point, button: "left", clickCount: 1 });
    await send("Input.dispatchMouseEvent", { type: "mouseMoved", x: point.x + dx, y: point.y + dy, button: "left", buttons: 1 });
    await send("Input.dispatchMouseEvent", { type: "mouseReleased", x: point.x + dx, y: point.y + dy, button: "left", clickCount: 1 });
    await pause(80);
  };
  await dragCover('.cover-sticker-frame', -40, -20);
  await dragCover('.cover-sticker-handle', 30, 20);
  await click("保存覆盖设置");
  await waitFor("document.body.innerText.includes('覆盖设置已应用')");
  const coverSettings = (await evaluate("window.jianji.getState()")).project.coverSticker;
  assert.ok(coverSettings.rectangle.x < 0.35 && coverSettings.rectangle.width > 0.3, "real pointer drag and resize update IPC settings");
  assert.deepEqual(coverSettings.stickerIds, [uploaded[0].id]);
  await screenshot("04b-cover-sticker");
  await unlink(uploadSource);
  await click("自动生成提示词");
  await waitFor("!document.querySelector('.generate-brief').disabled");
  assert.equal(briefRequests, 3);
  assert.equal(briefPayload.messages[1].content.filter(item => item.type === "image_url").length, 1, "brief generation sees the uploaded sticker image");
  assert.equal(JSON.stringify(briefPayload).includes(directory), false);
  await click("选择本地文件夹");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.completed') !== null");
  assert.equal(requests, 1);
  const state = await evaluate("window.jianji.getState()");
  const encoderLabels = { libx264: "CPU 编码", h264_nvenc: "NVIDIA GPU", h264_amf: "AMD GPU", h264_qsv: "Intel GPU" };
  assert.equal(await evaluate("document.querySelector('.engine-status').textContent"), `${encoderLabels[state.capabilities.videoEncoder]} · ${state.capabilities.executionLimits.exports} 路`);
  assert.equal(state.queue.batches[0].batch.tasks[0].status, "completed");
  assert.equal(JSON.stringify(state).includes("local-smoke-key"), false);
  assert.equal(state.agentRun.items[0].summary, "保留主体与手动价格");
  const savedJob = JSON.parse(await readFile(path.join(directory, "jobs", `${state.queue.batches[0].batch.id}.json`), "utf8"));
  assert.equal(savedJob.batch.templateSnapshot.productPrice, twoLinePrice);
  const coverLayer = savedJob.batch.templateSnapshot.layers.find(layer => layer.cover);
  assert.equal(coverLayer.cover.stickerId, uploaded[0].id);
  assert.equal(coverLayer.x, coverSettings.rectangle.x);
  assert.equal(coverLayer.cover.height, coverSettings.rectangle.height);
  assert.deepEqual(savedJob.batch.templateSnapshot.layers.filter(layer => layer.type === "text").map(layer => layer.content), [twoLinePrice]);
  assert.equal(savedJob.batch.templateSnapshot.layers.some(layer => layer.type === "sticker" && layer.assetPath === path.join(directory, "uploaded-stickers", `${uploaded[0].id}.png`)), true, "uploaded image survives source removal and real FFmpeg export");
  assert.deepEqual(savedJob.batch.templateSnapshot.layers.find(layer => layer.type === "text").shadow, { color: { r: 232, g: 70, b: 120, a: 1 }, xRatio: 0.004, yRatio: 0.005 }, "selected price appearance survives IPC and is frozen for retries");
  await screenshot("05-results");
  await click("模型与 API");
  await click("API 连接管理");
  await evaluate("document.querySelector('details').open = true");
  await click("读取可导入配置");
  await waitFor("document.body.innerText.includes('MiniMax fixture')");
  assert.equal(await evaluate("document.body.innerText.includes('cc-switch-fixture-key')"), false);
  await screenshot("06-cc-switch");
  await click("导入到简辑");
  await waitFor("document.querySelectorAll('.provider-choice').length === 3");
  await click("删除");
  await click("确认删除");
  await waitFor("document.querySelectorAll('.provider-choice').length === 2");
  assert.equal((await evaluate("window.jianji.getState()")).connection.configured, false);
  await evaluate("[...document.querySelectorAll('.provider-choice')].find(p => p.querySelector('strong').textContent.includes('MiniMax') && p.textContent.includes('使用此连接')).querySelector('button').click()");
  await waitFor("document.body.innerText.includes('把视频拖到这里')");
  const imported = await evaluate("window.jianji.getState()");
  assert.equal(imported.connection.source, "api");
  assert.equal(imported.connection.protocol, "anthropic");
  assert.equal(JSON.stringify(imported).includes("cc-switch-fixture-key"), false);
  await click("规则模板");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.failed') !== null");
  await writeFile(source, sourceBytes);
  await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent === '重试导出').click()");
  await waitFor("document.querySelector('.result-row .status-tag.running') !== null");
  const cancelAvailable = await evaluate("[...document.querySelectorAll('.result-row button')].some(button => button.textContent === '停止' && !button.disabled)");
  assert.equal(cancelAvailable, true, "Retry must leave cancellation available");
  await evaluate("[...document.querySelectorAll('.result-row button')].find(button => button.textContent === '停止').click()");
  await waitFor("document.querySelector('.result-row .status-tag.cancelled') !== null");
  assert.equal(await evaluate("document.querySelector('.result-row:has(.status-tag.cancelled)').innerText.includes('重试导出')"), false);
  assert.equal(requests, 2, "Export retry must not invoke the provider again");
  await waitFor("(async () => !(await window.jianji.getState()).project.hasUnsavedChanges)()");
  await click("新建创作");
  await waitFor("document.body.innerText.includes('你的素材即将在这里就位')");
  const historicalProject = structuredClone(savedCollection);
  historicalProject.id = crypto.randomUUID();
  const historicalBatch = structuredClone(savedJob.batch);
  historicalBatch.id = crypto.randomUUID();
  historicalBatch.projectId = historicalProject.id;
  historicalBatch.status = "active";
  historicalBatch.tasks = Array.from({ length: 57 }, () => ({
    id: crypto.randomUUID(), batchId: historicalBatch.id, mediaId: historicalProject.mediaItems[0].id,
    status: "queued", progress: 0, attempt: 0, createdAt: new Date().toISOString(), attempts: [],
  }));
  historicalProject.exportBatches = [historicalBatch];
  await writeFile(collectionFile, JSON.stringify(historicalProject));
  await click("打开其他素材集");
  await waitFor("document.body.innerText.includes('测试素材.mp4')");
  const reopened = await evaluate("window.jianji.getState()");
  assert.equal(reopened.queue.batches[0].batch.tasks.length, 57);
  assert.equal(reopened.queue.batches[0].batch.tasks.every(task => task.status === "interrupted"), true);
  await click("规则模板");
  assert.equal(await evaluate("[...document.querySelectorAll('.template-card')].every(button => !button.disabled)"), true, "abandoned queued jobs must not lock templates");
  assert.equal(await evaluate("document.querySelector('.model-picker input').disabled"), false, "abandoned jobs must not lock model selection");
  await click("清爽日常");
  assert.equal(await evaluate("document.querySelector('.template-card.clean').getAttribute('aria-pressed')"), "true");
  assert.equal(requests, 2, "opening a saved collection never restarts model work");
  assert.deepEqual(await readFile(source), sourceBytes, "recovery leaves the original video unchanged");
  await screenshot("07-reopened-collection-unlocked");
  await click("全部交给 Agent");
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await click("规则模板");
  assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button => button.textContent === '全部交给 Agent').getAttribute('aria-pressed')"), "true", "library navigation preserves automatic mode");
  assert.equal(await evaluate("document.querySelectorAll('[data-price-style]').length"), 0, "automatic mode hides the retained manual price style");
  await evaluate("document.querySelector('.directory-picker').click()");
  await waitFor("[...document.querySelectorAll('button')].some(button => button.textContent.includes('交给 Agent，制作') && !button.disabled)");
  await click("交给 Agent，制作");
  await waitFor("document.querySelector('.result-row .status-tag.completed') !== null");
  assert.equal(shortlistRequests, 1);
  assert.equal(requests, 3);
  const autoState = await evaluate("window.jianji.getState()");
  const autoBatch = autoState.queue.batches.find(batch => batch.batch.tasks.some(task => task.status === "completed"));
  const autoJob = JSON.parse(await readFile(path.join(directory, "jobs", `${autoBatch.batch.id}.json`), "utf8"));
  assert.equal(autoJob.batch.templateSnapshot.layers.some(layer => layer.type === "sticker" && layer.assetPath.endsWith(`${uploaded[0].id}.png`)), true, "Agent-selected upload reaches real FFmpeg output");
  assert.deepEqual(autoJob.batch.templateSnapshot.layers.find(layer => layer.type === "text").color, { r: 224, g: 253, b: 255, a: 1 }, "Agent-selected price appearance reaches the frozen automatic export");
  const uploadedPath = path.join(directory, "uploaded-stickers", `${uploaded[0].id}.png`);
  const frozenStickerBytes = await readFile(uploadedPath);
  await click("规则模板");
  await click("自己设置");
  await click("左上角");
  await evaluate("document.querySelector('select[aria-label=\"角落内容类型\"]').value = 'sticker'; document.querySelector('select[aria-label=\"角落内容类型\"]').dispatchEvent(new Event('change', { bubbles: true }))");
  await waitFor(`[...document.querySelectorAll('.sticker-choices button')].some(button => button.textContent === ${JSON.stringify(uploaded[0].label)})`);
  await click(uploaded[0].label);
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await evaluate("document.querySelector('.sticker-delete-actions button').click()");
  await click("取消");
  assert.equal(await evaluate("document.querySelectorAll('.uploaded-sticker-grid img').length"), 1, "cancel keeps the sticker");
  assert.equal(await evaluate("window.jianji.removeSticker('heart').then(() => false, () => true)"), true, "IPC cannot delete a builtin");
  await evaluate("document.querySelector('.sticker-delete-actions button').click()");
  await click("确认删除");
  await click("规则模板");
  await click("上传贴纸");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  await writeFile(path.join(directory, "delete.release"), "release");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 0");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.some(sticker => sticker.id === uploaded[0].id), false);
  assert.deepEqual(await readFile(uploadedPath), frozenStickerBytes, "deletion preserves the frozen asset for export retries");
  assert.equal(await evaluate(`window.jianji.generateBrief({ruleId:'clean',decorations:{mode:'manual',sticker:${JSON.stringify(uploaded[0].id)},productPrice:'19.90'}}).then(() => false, () => true)`), true, "deleted upload cannot reach a new model request");
  assert.equal(briefRequests, 3);
  await click("规则模板");
  assert.equal(await evaluate("document.querySelector('select[aria-label=\"角落内容类型\"]').value"), "none", "deleting clears explicit corner selection");
  await click("默认样式");
  await waitFor("document.querySelector('.sticker-choices button[aria-pressed=true]')?.textContent === '不加贴纸'");
  assert.equal(await evaluate("document.querySelector('#product-price').value"), twoLinePrice);
  await writeFile(uploadSource, frozenStickerBytes);
  await click("上传贴纸");
  await click("选择图片上传");
  await waitFor("document.querySelectorAll('.uploaded-sticker-grid img').length === 1");
  assert.equal((await evaluate("window.jianji.decorationCatalog()")).stickers.some(sticker => sticker.id === uploaded[0].id), true, "reimport restores a removed upload");
  await screenshot("08-sticker-delete-restored");
  assert.deepEqual(exceptions, []);
  const codexPid = Number(await readFile(path.join(directory, "codex.pid"), "utf8"));
  const exit = new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("Application did not finish shutdown")), 10_000);
    child.once("exit", (code) => { clearTimeout(timer); resolve(code); });
  });
  await writeFile(path.join(directory, "index-failure"), "fail index writes only");
  await evaluate("window.jianji.renameProject('退出保存测试')");
  await writeFile(path.join(directory, "quit.signal"), "quit");
  assert.equal(await exit, 0);
  assert.throws(() => process.kill(codexPid, 0), { code: "ESRCH" }, "App must wait for its Codex child to exit");
  console.log(JSON.stringify({ result: "PASS", providerRequests: requests, briefRequests, shortlistRequests, screenshotDirectory: directory, output: state.queue.batches[0].batch.tasks[0].outputPath, runtimeExceptions: exceptions }, null, 2));
} catch (error) {
  console.error(processLog.slice(-3000));
  throw error;
} finally {
  socket?.close();
  child.kill("SIGKILL");
  try {
    const pid = Number(await readFile(path.join(directory, "codex.pid"), "utf8"));
    if (Number.isSafeInteger(pid) && pid > 0) {
      const owned = process.platform !== "linux" || (await readFile(`/proc/${pid}/cmdline`, "utf8")).includes(path.join(root, "tests/fixtures/codex-app-server.cjs"));
      if (owned) process.kill(pid, "SIGKILL");
    }
  } catch { /* The task-owned fixture has already exited. */ }
  server.closeAllConnections();
  await new Promise((resolve) => server.close(resolve));
}
